#include "tlpp-core.th"

namespace totvs.protheus.backoffice.reconciliation.userprofile

//-------------------------------------------------------------------
/*/{Protheus.doc} UserProfileService
Classe de servico, realizada instancia e chamada de metodos de servicos

@author Totvs
/*/
//-------------------------------------------------------------------
class UserProfileService
public method new()
public method getInstance()
public method postUserProfileByBody()
public method getUserProfile()
endclass

//-------------------------------------------------------------------
/*/{Protheus.doc} UserProfileService
Metodo construtor

@author Totvs
/*/
//-------------------------------------------------------------------
method new() class UserProfileService
return

//-------------------------------------------------------------------
/*/{Protheus.doc} getInstance
Responsavel por instanciar a classe controller

@author Totvs
/*/
//-------------------------------------------------------------------

method getInstance() class UserProfileService
static __instance as Object

If ValType(__instance) == "U"
    __instance := UserProfileService():new()
EndIf
return

//-------------------------------------------------------------------
/*/{Protheus.doc} postUserProfileByBody
Responsavel por chamar a consulta e parsear o retorno no formato JSON
Post
@author Totvs
/*/
//-------------------------------------------------------------------
method postUserProfileByBody(jBody as Json) class UserProfileService
    Local oUserProfile := UserProfileProtheusData():getData()    
    Local aResponse := oUserProfile:postProfileByBody(jBody)
    FreeObj(oUserProfile)
return aResponse

//-------------------------------------------------------------------
/*/{Protheus.doc} getUserProfileByBody
Responsavel por chamar a consulta e parsear o retorno no formato JSON
Get
@author Totvs
/*/
//-------------------------------------------------------------------
method getUserProfile(cParamType as Character) class UserProfileService
    Local oUserProfile := UserProfileProtheusData():getData() as Object
    Local aResponse := {} as Array
    
    Default cParamType := ""

    aResponse := oUserProfile:getProfile(cParamType)
    FreeObj(oUserProfile)
return aResponse
