#include 'tlpp-core.th'
#include 'tlpp-rest.th'

namespace tr.BranchCode
using namespace tr.util
using namespace tr.BranchCode.Service
/* 
//-------------------------------------------------------------------
//  {Protheus.doc} totvsRecibos/BranchCode
//	EndPoint
//	URL /api/v1/totvsRecibos/branchcode/
//
//@author José González
//@since 02/02/2022
/*/
//-------------------------------------------------------------------
class BranchCodeController

public method New()

@GET('/api/v1/totvsRecibos/branchCode/:group')
public method BranchCodeRec() 

endClass
//-------------------------------------------------------------------
/*{Protheus.doc} totvsRecibos/branchcode
new
Constructor de la clase

@author José González
@since 02/02/2022
/*/
//-------------------------------------------------------------------
Method new() class BranchCodeController
     
return 

//-------------------------------------------------------------------
/*/{Protheus.doc} totvsRecibos/branchcode
EndPoint  para obtener las filiales

@author José González
@since 02/02/2022
/*/
//-------------------------------------------------------------------

Method BranchCodeRec() Class BranchCodeController

Local oBranchCodeService as Object
Local oResponse as Object
	
oBranchCodeService := BranchCodeService():new()
oResponse := oBranchCodeService:branchcodeServices(oRest:getPathParamsRequest())
AnswerRest(oResponse)
	
Return .T.
