#INCLUDE "TLPP-CORE.TH"
#INCLUDE "TLPP-REST.TH"

namespace totvs.protheus.retail.rmi.api.notasaidaapi

using namespace totvs.protheus.retail.rmi.api.notasaidaobj

//-------------------------------------------------------------------
/*/{Protheus.doc}
    API para consulta de Notas Fiscais de Saída do Varejo
/*/
//-------------------------------------------------------------------

/* ----------------------------------------- */
@Post("api/retail/v1/notasaida/lista")
Function lista()

    Local oNotaSaida := NotaSaidaObj():new(oRest, oRest:getQueryRequest(), oRest:getBodyRequest())

    oNotaSaida:get()
    
Return oRest:setResponse( oNotaSaida:getReturn() )