#INCLUDE "locr005.ch" 
#INCLUDE "PROTHEUS.CH"   

/*/{PROTHEUS.DOC} LOCR005.PRW
ITUP BUSINESS - TOTVS RENTAL
RELATORIO DISPONIBILIDADE DE FROTA - CAIXA DE PROCESSO
@TYPE FUNCTION
@AUTHOR FRANK ZWARG FUGA
@SINCE 03/12/2020
@VERSION P12
@HISTORY 03/12/2020, FRANK ZWARG FUGA, FONTE PRODUTIZADO.
/*/
    
FUNCTION LOCR005()
LOCAL CDESC1         	:= STR0001 //"ESTE PROGRAMA TEM COMO OBJETIVO IMPRIMIR RELATORIO "
LOCAL CDESC2         	:= STR0002 //"DE ACORDO COM OS PARAMETROS INFORMADOS PELO USUARIO."
LOCAL CDESC3         	:= STR0003 //"DISPONIBILIDADE DE FROTA - CAIXA DE PROCESSO"
LOCAL TITULO       		:= STR0003 //"DISPONIBILIDADE DE FROTA - CAIXA DE PROCESSO"
LOCAL NLIN         		:= 80
//LOCAL CPERG        		:= "LOCP061"
LOCAL CPERG        		:= "LOCR005"
LOCAL CABEC2       		:= ""
LOCAL AORD 				:= {}       
LOCAL IMPRIME  

PRIVATE CABEC1       	:= ""
PRIVATE LEND         	:= .F.
PRIVATE LABORTPRINT  	:= .F.
PRIVATE LIMITE          := 120
PRIVATE TAMANHO         := "G"
PRIVATE NOMEPROG        := "LOCDISFRV1_3" // COLOQUE AQUI O NOME DO PROGRAMA PARA IMPRESSAO NO CABECALHO
PRIVATE NTIPO           := 18
PRIVATE ARETURN         := { "ZEBRADO", 1, "ADMINISTRACAO", 2, 2, 1, "", 1}
PRIVATE NLASTKEY        := 0
PRIVATE CBTXT      		:= SPACE(10)
PRIVATE CBCONT     		:= 00
PRIVATE CONTFL     		:= 01
PRIVATE M_PAG      		:= 01
PRIVATE WNREL      		:= "LOCDISFRV13" // COLOQUE AQUI O NOME DO ARQUIVO USADO PARA IMPRESSAO EM DISCO
PRIVATE CSTRING 		:= ""

IMPRIME := .T. 

//VALIDPERG(CPERG)
PERGUNTE(CPERG,.T.)

WNREL := SETPRINT(CSTRING,NOMEPROG,CPERG,@TITULO,CDESC1,CDESC2,CDESC3,.T.,AORD,.T.,TAMANHO,,.T.)

IF EMPTY(MV_PAR03) .OR. EMPTY(MV_PAR04) 
	MSGALERT(STR0004, STR0005)  //"PERIODO INICIAL OU FINAL ESTA EM BRANCO... PREENCHER !"###"LOCR005.PRW"
	RETURN
ENDIF

IF NLASTKEY == 27
	RETURN
ENDIF

SETDEFAULT(ARETURN,CSTRING)

IF NLASTKEY == 27
   RETURN
ENDIF

NTIPO := IF(ARETURN[4]==1,15,18)

RPTSTATUS({|| RUNREPORT(CABEC1,CABEC2,TITULO,NLIN) },TITULO)

RETURN                             

/*
‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±⁄ƒƒƒƒƒƒƒƒƒƒ¬ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒø±±
±±≥DESCRIáÖO ≥ PROCESSAMENTO E EXECUCAO DO RELATORIO                        ≥±±
±±√ƒƒƒƒƒƒƒƒƒƒ≈ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ¥±±
±±≥ USO      ≥ ESPECIFICO GPO                                               ≥±±
±±¿ƒƒƒƒƒƒƒƒƒƒ¡ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒŸ±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ
*/

STATIC FUNCTION RUNREPORT(CABEC1,CABEC2,TITULO,NLIN)

LOCAL CHTML		:= ""
Local cLocal	:= ""
Local nX		:= 0
Local cInMvPar05:= ""
Local cDeParaSt	:= ""
Local cSubAux	:= ""
Local cPicHora 	:= X3Picture( "FPF_HORAI" )
Local cFrotAux	:= ""
Local cTamFrot	:= TamSx3("FPF_FROTA")[1]
Local cTamNome	:= 30
Local EXISTF	:= .F.
Local dDataLinha:= MV_PAR03
  
CQRYWHER := ""

//Monta string para where com MV_PAR05
For nX := 1 To Len(AllTrim(MV_PAR05)) 
	cSubAux := SubStr(AllTrim(MV_PAR05),nX,1)
	If cSubAux <> "*"
		//j· preencheu um, adiciona separador
		If !Empty(cInMvPar05)
			cInMvPar05 	+= ","
		EndIf
		If !Empty(cDeParaSt)
			cDeParaSt 	+= "|"
		EndIf
		//adiciona seleÁ„o
		cInMvPar05	+= "'" + cSubAux + "'"
		cDeParaSt	+= cSubAux
	EndIF
Next nX

//If  !(EMPTY(MV_PAR05)) .And. !(MV_PAR05 $ "5") //1-Prevista;2-Baixada;3-Encerrada;4-Medida;5-Disponivel
	CQRYWHER += " ( (FPF.FPF_DATA <= "  + DTOS(MV_PAR03) + " AND FPF.FPF_DATA <= " + DTOS(MV_PAR04)  + " AND FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + "  AND FPF.FPF_DATA >= " + DTOS(MV_PAR04) + " ) OR "	
	CQRYWHER += "   (FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + " AND FPF.FPF_DATA <= " + DTOS(MV_PAR04)  + " AND FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + "  AND FPF.FPF_DATA <= " + DTOS(MV_PAR04) + " ) OR "	
	CQRYWHER += "   (FPF.FPF_DATA <= "  + DTOS(MV_PAR03) + " AND FPF.FPF_DATA <= " + DTOS(MV_PAR04)  + " AND FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + "  AND FPF.FPF_DATA <= " + DTOS(MV_PAR04) + " ) OR "	
	CQRYWHER += "   (FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + " AND FPF.FPF_DATA <= " + DTOS(MV_PAR04)  + " AND FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + "  AND FPF.FPF_DATA >= " + DTOS(MV_PAR04) + " ) )  AND "	
//EndIf

CQRYWHER += " FPF.FPF_AS BETWEEN   '" + MV_PAR06 + "' AND '" + MV_PAR07 + "'" + CRLF
CQRYWHER += " AND FPF.FPF_OBRA   BETWEEN   '"+MV_PAR12+"' AND '"+MV_PAR13+"'" + CRLF
CQRYWHER += " AND FPF.D_E_L_E_T_ = '' AND FPF_FROTA <> '' " + CRLF                                                                              

CQRYCLI := " AND ((FQ5.FQ5_CODCLI BETWEEN '"+MV_PAR08+"' AND '"+MV_PAR09+"'" + CRLF
CQRYCLI += " AND FQ5.FQ5_LOJA BETWEEN   '"+MV_PAR10+"' AND '"+MV_PAR11+"') 

IF EMPTY(MV_PAR05)
	CQRYCLI += " OR (FQ5_CODCLI = '' AND FQ5_LOJA = '' ) " + CRLF// AND FPO_STATUS IN ('C','9')
ENDIF

CQRYCLI += " )" + CRLF

// MONTA ARQUIVO DE TRABALHO DE APOIO PARA DISPONIBILIDADES
CQRYWHER := ""
//IF MV_PAR05 <> "1"
//If  !(EMPTY(cInMvPar05)) .And. !("5" $ cInMvPar05) //1-Prevista;2-Baixada;3-Encerrada;4-Medida;5-Disponivel
	CQRYWHER += " ( (FPF.FPF_DATA <= "  + DTOS(MV_PAR03) + " AND FPF.FPF_DATA <= " + DTOS(MV_PAR04)  + " AND FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + "  AND FPF.FPF_DATA >= " + DTOS(MV_PAR04) + " ) OR "	// PERÕODO TOTALMENTE DENTRO DO LAN«AMENTO
	CQRYWHER += "   (FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + " AND FPF.FPF_DATA <= " + DTOS(MV_PAR04)  + " AND FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + "  AND FPF.FPF_DATA <= " + DTOS(MV_PAR04) + " ) OR "	// PERÕODO TOTALMENTE FORA DO LAN«AMENTO
	CQRYWHER += "   (FPF.FPF_DATA <= "  + DTOS(MV_PAR03) + " AND FPF.FPF_DATA <= " + DTOS(MV_PAR04)  + " AND FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + "  AND FPF.FPF_DATA <= " + DTOS(MV_PAR04) + " ) OR "	// LAN«AMENTO TERMINA NO PERÕODO
	CQRYWHER += "   (FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + " AND FPF.FPF_DATA <= " + DTOS(MV_PAR04)  + " AND FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + "  AND FPF.FPF_DATA >= " + DTOS(MV_PAR04) + " ) )  AND "	// LAN«AMENTO INICIA NO PERÕODO
//ENDIF
CQRYWHER += " FPF.FPF_AS BETWEEN   '"+MV_PAR06+"' AND '"+MV_PAR07+"'" + CRLF
CQRYWHER += " AND FPF.FPF_OBRA BETWEEN   '"+MV_PAR12+"' AND '"+MV_PAR13+"'" + CRLF
CQRYWHER += " AND FPF.D_E_L_E_T_ = '' AND FPF_FROTA <> '' " + CRLF                                                                              

CQRYCLI := " AND ((FQ5.FQ5_CODCLI BETWEEN '"+MV_PAR08+"' AND '"+MV_PAR09+"'" + CRLF
CQRYCLI += " AND FQ5_LOJA BETWEEN   '"+MV_PAR10+"' AND '"+MV_PAR11+"') 
IF EMPTY(cInMvPar05)
	CQRYCLI += " OR (FQ5_CODCLI = '' AND FQ5_LOJA = '' ) " + CRLF// AND FPO_STATUS IN ('C','9')
ENDIF
CQRYCLI += " )" + CRLF
   
CQRYWHT9 := " AND T9_CODBEM  BETWEEN '"+MV_PAR01+"' AND '"+MV_PAR02+"' AND  T9_SITBEM='A' AND T9_TIPOSE IN ('E','L','M','P') " + CRLF

CTMPCLI := CRIATRAB(,.F.)
CQRYINT := "SELECT DISTINCT FPF_FROTA , FPF_DATA "
CQRYINT += "INTO  " + CTMPCLI + CRLF
CQRYINT += "FROM "+ RETSQLNAME("FPF") + " FPF " + CRLF
CQRYINT += "JOIN "+ RETSQLNAME("ST9") + " T9 ON T9_CODBEM = FPF_FROTA  AND T9.D_E_L_E_T_= '' " + CRLF
CQRYINT += "WHERE "+ CQRYWHER+CQRYCLI+CQRYWHT9 + " AND FPF_STATUS NOT IN ('A','E','S') " //APROVEITA MONTAGEM DE CONDICAO FEITA ANTERIORMENTE
CQRYINT += "AND FPF.D_E_L_E_T_= '' "
CQRYINT += "ORDER BY 1,2,3   
TCSQLEXEC(CQRYINT)

CQRYINT := "SELECT DISTINCT FPF_FROTA , FPF_DATA "
CQRYINT += "FROM "+ RETSQLNAME("FPF") + " FPF " + CRLF
CQRYINT += "JOIN "+ RETSQLNAME("ST9") + " T9 ON T9_CODBEM = FPF_FROTA  AND T9.D_E_L_E_T_= '' " + CRLF
CQRYINT += "LEFT JOIN "+ RETSQLNAME("FQ5") + " FQ5 ON FPF_AS = FQ5_AS AND FQ5.D_E_L_E_T_ = '' " + CRLF
CQRYINT += "WHERE "+ CQRYWHER+CQRYWHT9 + " AND FPF_STATUS NOT IN ('A','E','S','C') " //APROVEITA MONTAGEM DE CONDICAO FEITA ANTERIORMENTE
CQRYINT += "AND FPF.D_E_L_E_T_= '' "
CQRYINT += "ORDER BY 1,2,3   "

CQUERY := "SELECT DISTINCT FPF_FROTA , T9_CODFA,SUBSTRING(T9_NOME,1,30) T9_NOME, A1_NREDUZ, FQ5_DESTIN, FPF_DATA, " + CRLF
//CQUERY += "       UPPER(SUBSTRING(X5_DESCRI,1,11)) STAT_FR,"+ CRLF
CQUERY += "       RTRIM(SUBSTRING(A1_NOME,1,30))+'/'+ISNULL(RTRIM(SUBSTRING(FP1_NOMORI,1,30)),'')  CLI_OBRA, " + CRLF
CQUERY += "       ISNULL(LTRIM(SUBSTRING(FP1_MUNORI,1,20))+ '/'+ FP1_ESTORI,'') MUN_OBRA, FPF_STATUS, 'B' ORIGEM, FQ5_CODCLI, FQ5_LOJA " + CRLF
CQUERY += "       , FPF_HORAI, FPF_HORAF " + CRLF
CQUERY += "FROM "+ RETSQLNAME("FPF") + " FPF " + CRLF
CQUERY += "JOIN "+ RETSQLNAME("ST9") + " T9 ON T9_CODBEM = FPF.FPF_FROTA  AND T9.D_E_L_E_T_ = ''" + CRLF
//CQUERY += "LEFT JOIN "+ RETSQLNAME("SX5") + " STAT ON X5_TABELA = 'ZL' AND FPF_STATUS = X5_CHAVE AND STAT.D_E_L_E_T_ = '' " + CRLF
CQUERY += "LEFT JOIN "+ RETSQLNAME("FP1") + " ZA1 ON FP1_PROJET = FPF_PROJET  AND FP1_OBRA = FPF_OBRA AND ZA1.D_E_L_E_T_ = '' "+CRLF
CQUERY += "LEFT JOIN "+ RETSQLNAME("FQ5") + " FQ5 ON FPF_AS = FQ5_AS AND FQ5.D_E_L_E_T_ = '' " + CRLF
CQUERY += "LEFT JOIN "+ RETSQLNAME("SA1") + " SA1 ON A1_FILIAL = '" + FwFilial("SA1") + "' AND SA1.D_E_L_E_T_ = ' ' AND A1_COD = FQ5_CODCLI AND A1_LOJA = FQ5_LOJA " + CRLF
CQUERY += "WHERE " + CQRYWHER+CQRYWHT9 //APROVEITA MONTAGEM DE CONDICAO FEITA ANTERIORMENTE

//IF !EMPTY(MV_PAR05) .AND. MV_PAR05=="1"
IF !EMPTY(cInMvPar05) .AND. "5" $ cInMvPar05  //1-Prevista;2-Baixada;3-Encerrada;4-Medida;5-Disponivel
	CRESFIL := ""
	CQRYFIL := "SELECT DISTINCT FPF_FROTA  "
	CQRYFIL += "FROM "+RETSQLNAME("FPF") + " FPF "
	CQRYFIL += "LEFT JOIN "+ RETSQLNAME("FQ5") + " FQ5 ON FPF_AS = FQ5_AS AND FQ5.D_E_L_E_T_ = '' " + CRLF
	CQRYFIL += "WHERE "
	CQRYFIL += "((FPF.FPF_DATA <= "  + DTOS(MV_PAR03) + " AND FPF.FPF_DATA <= " + DTOS(MV_PAR04)  + " AND FPF.FPF_DATA >= " + DTOS(MV_PAR03) + "  AND FPF.FPF_DATA >= " + DTOS(MV_PAR04) + ") OR "	// PERÕODO TOTALMENTE DENTRO DO LAN«AMENTO
	CQRYFIL += "(FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + " AND FPF.FPF_DATA <= " + DTOS(MV_PAR04)  + " AND FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + "  AND FPF.FPF_DATA <= " + DTOS(MV_PAR04) + ") OR "	// PERÕODO TOTALMENTE FORA DO LAN«AMENTO
	CQRYFIL += "(FPF.FPF_DATA <= "  + DTOS(MV_PAR03) + " AND FPF.FPF_DATA <= " + DTOS(MV_PAR04)  + " AND FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + "  AND FPF.FPF_DATA <= " + DTOS(MV_PAR04) + ") OR "	// LAN«AMENTO TERMINA NO PERÕODO
	CQRYFIL += "(FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + " AND FPF.FPF_DATA <= " + DTOS(MV_PAR04)  + " AND FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + "  AND FPF.FPF_DATA >= " + DTOS(MV_PAR04) + "))  AND  "	// LAN«AMENTO INICIA NO PERÕODO
	CQRYFIL += "FPF.FPF_AS BETWEEN   '"+MV_PAR06+"' AND '"+MV_PAR07+"' " + CRLF
	CQRYFIL += "AND FPF.FPF_OBRA BETWEEN   '"+MV_PAR12+"' AND '"+MV_PAR13+"' " + CRLF
	CQRYFIL += "AND FPF.D_E_L_E_T_ = ''  AND FPF_FROTA = '' " + CRLF                                                                              
	CQRYFIL += "AND ((FQ5_CODCLI BETWEEN '"+MV_PAR08+"' AND '"+MV_PAR09+"' "+ CRLF
	CQRYFIL += "AND FQ5_LOJA BETWEEN   '"+MV_PAR10+"' AND '"+MV_PAR11+"') )
	CQRYFIL := CHANGEQUERY(CQRYFIL)
	DBUSEAREA(.T., "TOPCONN", TCGENQRY(,,CQRYFIL), "TRBFIL", .F., .T.)
	IF !TRBFIL->(EOF())
		CRESFIL += "("
		WHILE !TRBFIL->(EOF())
			CRESFIL += "'"+ALLTRIM(TRBFIL->FPF_FROTA )+"',"
			TRBFIL->(DBSKIP())
		ENDDO
	ENDIF
	TRBFIL->(DBCLOSEAREA())
	CRESFIL := SUBSTR(CRESFIL,1,LEN(CRESFIL)-1)+")" 

	/*IF !EMPTY(CRESFIL)
		CQUERY += "	UNION " + CRLF
		CQUERY += "	SELECT FPF_FROTA , T9_CODFA,SUBSTRING(T9_NOME,1,30) T9_NOME, A1_NREDUZ, FQ5_DESTIN, FPF_DATA, " + CRLF
		//CQUERY += "	       UPPER(SUBSTRING(X5_DESCRI,1,11)) STAT_FR," + CRLF
		CQUERY += "	       RTRIM(SUBSTRING(A1_NOME,1,30))+'/'+ISNULL(RTRIM(SUBSTRING(FP1_NOMORI,1,30)),'')  CLI_OBRA, " + CRLF
		CQUERY += "	       ISNULL(LTRIM(SUBSTRING(FP1_MUNORI,1,20))+ '/'+ FP1_ESTORI,'') MUN_OBRA, FPF_STATUS, 'B' ORIGEM, FQ5_CODCLI, FQ5_LOJA " + CRLF
		CQUERY += "       , FPF_HORAI, FPF_HORAF " + CRLF
		CQUERY += "	FROM " + RETSQLNAME("FPF")+ " FPF " + CRLF
		CQUERY += "	JOIN " + RETSQLNAME("ST9")+ " T9 ON T9_CODBEM = FPF.FPF_FROTA  AND T9.D_E_L_E_T_ = '' " + CRLF
		//CQUERY += "	LEFT JOIN " + RETSQLNAME("SX5")+ " STAT ON X5_TABELA = 'ZL' AND FPF_STATUS = X5_CHAVE AND STAT.D_E_L_E_T_ = '' " + CRLF
		CQUERY += "	LEFT JOIN " + RETSQLNAME("FP1")+ " ZA1 ON FP1_PROJET = FPF_PROJET  AND FP1_OBRA = FPF_OBRA AND ZA1.D_E_L_E_T_ = '' 	" + CRLF
		CQUERY += " LEFT JOIN " + RETSQLNAME("FQ5")+ " FQ5 ON FPF_AS = FQ5_AS AND FQ5.D_E_L_E_T_ = ''	" + CRLF
		CQUERY += "LEFT JOIN "+ RETSQLNAME("SA1") + " SA1 ON A1_FILIAL = '" + FwFilial("SA1") + "' AND SA1.D_E_L_E_T_ = ' ' AND A1_COD = FQ5_CODCLI AND A1_LOJA = FQ5_LOJA " + CRLF
		CQUERY += "	WHERE " + CRLF
		CQUERY += " FPF.D_E_L_E_T_ = '' " + CRLF
		CQUERY += " AND T9_CODBEM  BETWEEN '"+MV_PAR01+"' AND '"+MV_PAR02+"' AND  T9_SITBEM='A' AND T9_TIPOSE IN ('G','U','M','P') " + CRLF
		//CQUERY += " AND FPF_STATUS BETWEEN '"+MV_PAR05+"' AND '"+MV_PAR06+"' AND FPF_FROTA  IN " + CRESFIL + " " + CRLF
		CQUERY += " AND FPF_FROTA  IN " + CRESFIL + " " + CRLF
		If !Empty(cInMvPar05)
			CQUERY += " AND FPF_STATUS IN (" + cInMvPar05 + ") " + CRLF
		EndIf
		If !Empty(DtoS(MV_PAR03)) .And. !Empty(DtoS(MV_PAR04))
			CQUERY += " AND FPF_DATA BETWEEN '" +  DtoS(MV_PAR03) + "' AND '" +  DtoS(MV_PAR04) + "' " + CRLF
		EndIf
	ENDIF*/
	
ENDIF

//IF MV_PAR05 <= '1' .AND. MV_PAR06 >= '1' 
IF "5" $ cInMvPar05 .Or. Empty(cInMvPar05)  //1-Prevista;2-Baixada;3-Encerrada;4-Medida;5-Disponivel
	//-->> CONSIDERA DISPONIVEL EM TODO O PERIODO TODOS OS BENS QUE NAO FOREM ENCONTRADOS NO FPF       
	//-->> SO VAI EXISTIR ESSE UNION CASO OS PARAMETROS   DO FPF FOREM <BRANCO> A <ZZZZ> 
	IF EMPTY(MV_PAR08+MV_PAR10+MV_PAR12)
		CQUERY += "UNION ALL" + CRLF
		CQUERY += "SELECT T9_CODBEM, T9_CODFA,SUBSTRING(T9_NOME,1,30) T9_NOME,'', '', '"+DTOS(MV_PAR03)+"', FQ5_CODCLI, '', FPF_STATUS, 'AA' ORIGEM, FQ5_CODCLI, FQ5_LOJA, '0000','2359'" + CRLF	
		CQUERY += "FROM "+ RETSQLNAME("ST9") + " T9 " + CRLF
		CQUERY += "LEFT JOIN "+ RETSQLNAME("FPF") + " FPF ON T9_CODBEM = FPF.FPF_FROTA  AND FPF.D_E_L_E_T_ = '' " + CRLF      
		CQUERY += "LEFT JOIN " + RETSQLNAME("FQ5")+ " FQ5 ON FPF_AS = FQ5_AS AND FQ5.D_E_L_E_T_ = ''	 AND " + CRLF
   		CQUERY += CQRYWHER+CQRYCLI + CRLF 
		CQUERY += "WHERE FPF_OBRA IS NULL  AND T9.D_E_L_E_T_ = ''" + CRLF		
    	CQUERY +=  CQRYWHT9
	ENDIF     
ENDIF  

/*IF !EMPTY(MV_PAR08) .AND. !EMPTY(MV_PAR10) 
	CQUERY += "UNION ALL " + CRLF
	CQUERY += "SELECT FPF_FROTA , T9_CODFA,SUBSTRING(T9_NOME,1,30) T9_NOME, A1_NREDUZ, FQ5_DESTIN, FPF_DATA, " + CRLF
	//CQUERY += "       UPPER(SUBSTRING(X5_DESCRI,1,11)) STAT_FR,"+ CRLF
	CQUERY += "       RTRIM(SUBSTRING(A1_NOME,1,30))+'/'+ISNULL(RTRIM(SUBSTRING(FP1_NOMORI,1,30)),'')  CLI_OBRA, " + CRLF
	CQUERY += "       ISNULL(LTRIM(SUBSTRING(FP1_MUNORI,1,20))+ '/'+ FP1_ESTORI,'') MUN_OBRA, FPF_STATUS, 'B' ORIGEM, FQ5_CODCLI, FQ5_LOJA " + CRLF	
	CQUERY += "       , FPF_HORAI, FPF_HORAF " + CRLF
	CQUERY += "FROM "+ RETSQLNAME("FPF") + " FPF " + CRLF
	CQUERY += "JOIN "+ RETSQLNAME("ST9") + " T9 ON T9_CODBEM = FPF.FPF_FROTA  AND T9.D_E_L_E_T_ = ''" + CRLF
	//CQUERY += "LEFT JOIN "+ RETSQLNAME("SX5") + " STAT ON X5_TABELA = 'ZL' AND FPF_STATUS = X5_CHAVE AND STAT.D_E_L_E_T_ = '' " + CRLF
	CQUERY += "LEFT JOIN "+ RETSQLNAME("FP1") + " ZA1 ON FP1_PROJET = FPF_PROJET  AND FP1_OBRA = FPF_OBRA AND ZA1.D_E_L_E_T_ = '' "+CRLF
	CQUERY += "LEFT JOIN " + RETSQLNAME("FQ5")+ " FQ5 ON FPF_AS = FQ5_AS AND FQ5.D_E_L_E_T_ = ''	" + CRLF
	CQUERY += "LEFT JOIN "+ RETSQLNAME("SA1") + " SA1 ON A1_FILIAL = '" + FwFilial("SA1") + "' AND SA1.D_E_L_E_T_ = ' ' AND A1_COD = FQ5_CODCLI AND A1_LOJA = FQ5_LOJA " + CRLF
	CQUERY += "WHERE  ((FPF.FPF_DATA <= "  + DTOS(MV_PAR03) + " AND FPF.FPF_DATA <= " + DTOS(MV_PAR04)  + " AND FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + "  AND FPF.FPF_DATA >= " + DTOS(MV_PAR04) + ") OR "	// PERÕODO TOTALMENTE DENTRO DO LAN«AMENTO
	CQUERY += " (FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + " AND FPF.FPF_DATA <= " + DTOS(MV_PAR04)  + " AND FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + "  AND FPF.FPF_DATA <= " + DTOS(MV_PAR04) + ") OR "	// PERÕODO TOTALMENTE FORA DO LAN«AMENTO
	CQUERY += " (FPF.FPF_DATA <= "  + DTOS(MV_PAR03) + " AND FPF.FPF_DATA <= " + DTOS(MV_PAR04)  + " AND FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + "  AND FPF.FPF_DATA <= " + DTOS(MV_PAR04) + ") OR "	// LAN«AMENTO TERMINA NO PERÕODO
	CQUERY += " (FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + " AND FPF.FPF_DATA <= " + DTOS(MV_PAR04)  + " AND FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + "  AND FPF.FPF_DATA >= " + DTOS(MV_PAR04) + ")) "	// LAN«AMENTO INICIA NO PERÕODO
	CQUERY += "AND FPF.FPF_AS BETWEEN   '"+MV_PAR06+"' AND '"+MV_PAR07+"'" + CRLF	
	CQUERY += "AND FPF.FPF_OBRA BETWEEN   '"+MV_PAR12+"' AND '"+MV_PAR13+"'" + CRLF
	CQUERY += "AND FPF.D_E_L_E_T_ = ''  AND FPF_FROTA = '' " + CRLF                                                                              
	CQUERY += "AND ((FQ5.FQ5_CODCLI BETWEEN '"+MV_PAR08+"' AND '"+MV_PAR09+"' " + CRLF
	CQUERY += "AND FQ5_LOJA <> '"+MV_PAR10+"' AND FQ5_CODCLI <> '' )) "
	CQUERY += "AND T9_CODBEM  BETWEEN '"+MV_PAR01+"' AND '"+MV_PAR02+"' AND  T9_SITBEM='A' AND T9_TIPOSE IN ('G','U','M','P') " + CRLF	
ENDIF*/

CQUERY += "ORDER BY 1, 5,6 " + CRLF 

IF SELECT("TRBFR") > 0
   TRBFR->(DBCLOSEAREA())
ENDIF 
CQUERY := CHANGEQUERY(CQUERY)
DBUSEAREA(.T., "TOPCONN", TCGENQRY(,,CQUERY), "TRBFR", .F., .T.)
TCSETFIELD("TRBFR","FPF_DATA","D",8,0)
//TCSETFIELD("TRBFR","FPF_DATA","D",8,0)

// --> MONTA CABECALHO COM TAMANHO DINAMICO PELO RESULTADO DA QUERY 
CABEC1 := PADR(STR0009       , LEN(TRBFR->FPF_FROTA )+1)  //"FROTA"
//CABEC1 += PADR("FANTASIA"  , LEN(TRBFR->T9_CODFA)+1)
CABEC1 += PADR(STR0010   , LEN(TRBFR->T9_NOME)+1) //"DESCRICAO"
//CABEC1 += PADR("STATUS"      , LEN(TRBFR->STAT_FR)+1)
CABEC1 += PADR(STR0011      , 11)  //"STATUS"
//CABEC1 += PADR("LOCALIDADE"  , LEN(TRBFR->FPO_LOCAL)+1)
//CABEC1 += PADR("LOCALIDADE"  , LEN(cLocal)+1)
CABEC1 += PADR(STR0012, LEN(TRBFR->CLI_OBRA)+1) //"CLIENTE/OBRA"
CABEC1 += PADR(STR0013, LEN(TRBFR->MUN_OBRA)+1) //"MUNICIPIO/UF"
//CABEC1 += PADR("DT INICIO"   , LEN(DTOC(TRBFR->FPF_DATA))+2)
//CABEC1 += PADR("DT FIM"      , LEN(DTOC(TRBFR->FPF_DATA)))
CABEC1 += PADR(STR0014      	, LEN(DTOC(TRBFR->FPF_DATA))+1) //"DATA"
CABEC1 += PADR(STR0015      , LEN(TRBFR->FPF_HORAI)+3) //"INICIO"
CABEC1 += PADR(STR0016      , LEN(TRBFR->FPF_HORAF)+3) //"FINAL"
  
// --> SETREGUA -> INDICA QUANTOS REGISTROS SERAO PROCESSADOS PARA A REGUA
SETREGUA(RECCOUNT())
CLOFRO  := ""
CLODTI  := ""
CLODTF  := ""     
CLO_MUN := ""          
CLO_CLI := ""            
CLOSTAT := ""
LSALTA  := .F.
NXXX    := ""
LCONTR  := .T.
LOK     := .T. 
 
//IF MV_PAR15 == 1							// SE FOR EXPORTAR PARA O EXCEL - CRISTIANE CAMPOS EM 11/11/2011
	// desativado por questoes dos debitos tecnicos - frank 06/04/2022
	/*
	CARQUIVO  := CRIATRAB(,.F.)+".HTM"		// ARQUIVO PADR√O HTML NA PASTA SERVER\SYSTEM
	NARQ      := FCREATE(CARQUIVO,0)		// ABERTURA DO ARQUIVO BIN¡RIO

	CHTML := "<HTML><HEAD><TITLE>DISPONIBILIDADE DE FROTAS</TITLE></HEAD>" + CRLFV
	CHTML += "<BODY><TABLE BORDER='1'><TR>"
	CHTML += "<TD COLSPAN='09'><CENTER><H2>DISPONIBILIDADE DE FROTAS</H2></CENTER>"
	CHTML += "PAR¬METROS: FROTA" + IF( EMPTY(MV_PAR01), "", " DE :"+MV_PAR01) + " AT…: " + MV_PAR02
	CHTML += " - PERIODO" + IF( EMPTY(MV_PAR03), "", " DE :"+DTOC(MV_PAR03))+ " AT…: " + DTOC(MV_PAR04)
	CHTML += " - STATUS: " + IF( EMPTY(MV_PAR05), "", " DE :"+MV_PAR05) + " AT…: " + MV_PAR06
	CHTML += " - ASG:" + IF( EMPTY(MV_PAR07), "", " DE :"+(MV_PAR07)) + " AT…: " + (MV_PAR08)
	CHTML += " - CLIENTE:" + IF( EMPTY(MV_PAR09), "", " DE :"+(MV_PAR09)) + " AT…: " + (MV_PAR10)
	CHTML += " - LOJA:" + IF( EMPTY(MV_PAR11), "", " DE :"+(MV_PAR11)) + " AT…: " + (MV_PAR12)
	CHTML += " - OBRA:" + IF( EMPTY(MV_PAR13), "", " DE :"+(MV_PAR13)) + " AT…: " + (MV_PAR14)
	CHTML += "</TD></TR><TR>"
	CHTML += "<TH>FROTA</TH>"
 //	CHTML += "<TH>FANTASIA</TH>"
	CHTML += "<TH>DESCRICAO</TH>"
	CHTML += "<TH>STATUS</TH>"
	CHTML += "<TH>LOCALIDADE</TH>" // 2011-11-17 - TOTVS GRU - DENIS - CORRECAO DA DESCRICAO NA EXPORTACAO
	CHTML += "<TH>CLIENTE/OBRA</TH>"
	CHTML += "<TH>MUNICIPIO/UF</TH>" // 2011-11-17 - TOTVS GRU - DENIS - CORRECAO DO POSICIONAMENTO DOS TITULOS DT INICIO E DT FIM
	CHTML += "<TH>DT INICIO</TH>"
	CHTML += "<TH>DT FIM</TH>"
	CHTML += "</TR>" + CRLF
	FWRITE(NARQ,CHTML,LEN(CHTML))
	*/
//ENDIF

IF TRBFR->(!EOF())
	EXISTF := .T.
ENDIF

IF !EXISTF
	TRBFR->(DBCLOSEAREA())
	//-->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
	//-->> CASO NAO TENHA NENHUMA INFORMA«√O NO ARRAY, CRIARA UM REGISTRO DE DISPONIBILIDADE 
	//-->> DE FROTA CONSIDERANDO O PERIODO DE DATA DO PARAMETRO
	//-->>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
	CQRY := " SELECT T9_CODBEM FPF_FROTA , T9_CODFA,SUBSTRING(T9_NOME,1,30) T9_NOME, A1_NREDUZ, FQ5_DESTIN, '"+DTOS(MV_PAR03)+"' FPF_DATA, '"+DTOS(MV_PAR04)+"' FPF_DATA, " + CRLF
	//CQRY += "        UPPER(SUBSTRING(X5_DESCRI,1,11)) STAT_FR, " + CRLF
	CQRY += "        LTRIM(SUBSTRING(A1_NOME,1,30))+'/'+ISNULL(LTRIM(SUBSTRING(FP1_NOMORI,1,30)),'')  CLI_OBRA, " + CRLF
	CQRY += "	     ISNULL(LTRIM(SUBSTRING(FP1_MUNORI,1,20))+ '/'+ FP1_ESTORI,'') MUN_OBRA, FPF_STATUS, 'B' ORIGEM, '1', FQ5_CODCLI, FQ5_LOJA " + CRLF
	CQRY += "       , FPF_HORAI, FPF_HORAF " + CRLF
	CQRY += " FROM " + RETSQLNAME("ST9") + "  T9 " + CRLF
	CQRY += "        LEFT JOIN " + RETSQLNAME("FPF") + " FPF ON T9_CODBEM = FPF.FPF_FROTA  AND T9.D_E_L_E_T_ = '' " + CRLF
	//CQRY += "        LEFT JOIN " + RETSQLNAME("SX5") + " STAT ON X5_TABELA = 'ZL' AND FPF_STATUS = X5_CHAVE AND STAT.D_E_L_E_T_ = '' " + CRLF
	CQRY += "        LEFT JOIN " + RETSQLNAME("FP1") + " ZA1 ON FP1_PROJET = FPF_PROJET  AND FP1_OBRA = FPF_OBRA AND ZA1.D_E_L_E_T_ = '' " + CRLF
	CQRY += "		 LEFT JOIN " + RETSQLNAME("FQ5") + " FQ5 ON FPF_AS = FQ5_AS AND FQ5.D_E_L_E_T_ = '' " + CRLF
	CQRY += "		 LEFT JOIN " + RETSQLNAME("SA1") + " SA1 ON A1_FILIAL = '" + FwFilial("SA1") + "' AND SA1.D_E_L_E_T_ = ' ' AND A1_COD = FQ5_CODCLI AND A1_LOJA = FQ5_LOJA " + CRLF
	CQRY += " WHERE  T9.D_E_L_E_T_ = '' " + CRLF
	CQRY += "   AND  T9_CODBEM BETWEEN '"+MV_PAR01+"' AND '"+MV_PAR02+"' AND T9_SITBEM='A' " + CRLF
	CQRY += "   AND  FPF_FROTA = '' " + CRLF
	CQRY += " AND FPF_DATA BETWEEN '" +  DtoS(MV_PAR03) + "' AND '" +  DtoS(MV_PAR03) + "' " + CRLF
	CQRY += " ORDER BY T9_CODBEM" + CRLF
	DBUSEAREA(.T., "TOPCONN", TCGENQRY(,,CHANGEQUERY(CQRY)), "TRBFR", .F., .T.)

	TCSETFIELD("TRBFR","FPF_DATA","D",8,0)
	//TCSETFIELD("TRBFR","FPF_DATA","D",8,0)
ENDIF

IF TRBFR->(!EOF())
	EXISTF := .T.
	DDTFIM := TRBFR->FPF_DATA
	CFANT  := TRBFR->T9_CODFA
	CLOFRO := TRBFR->FPF_FROTA
	CNOME  := TRBFR->T9_NOME
	NCONT  := 0
ENDIF

IF EMPTY(CLODTF)
	CLODTF := MV_PAR04-1
ENDIF

//Roda os resultados
WHILE TRBFR->(!EOF())
	
    // --> VERIFICA O CANCELAMENTO PELO USUARIO...
    IF LABORTPRINT
		@NLIN,00 PSAY "*** " + STR0017 + " ***" //CANCELADO PELO OPERADOR
		EXIT
	ENDIF     

   // --> IMPRESSAO DO CABECALHO DO RELATORIO... 
   IF NLIN > 55 // SALTO DE P¡GINA. NESTE CASO O FORMULARIO TEM 55 LINHAS...
      CABEC(TITULO,CABEC1,CABEC2,NOMEPROG,TAMANHO,NTIPO)
      NLIN := 8
   ENDIF     

    //IF TRBFR->FPF_STATUS >= MV_PAR05 .AND. TRBFR->FPF_STATUS<= MV_PAR06      
    IF ( !Empty(cDeParaSt) .And. TRBFR->FPF_STATUS $ cDeParaSt ) .Or. Empty(cDeParaSt) .Or. Empty(TRBFR->FPF_STATUS)

	  IF !(CLOFRO == TRBFR->FPF_FROTA  .AND. TRBFR->FPF_DATA < CLODTF .AND. TRBFR->ORIGEM <> 'B')

		//IF !(CLOFRO == TRBFR->FPF_FROTA)
			//Se for Status vazio ou 5-DisponÌvel, apresenta data se n„o retornou na Query
			If (Empty(cDeParaSt) .Or. "5" $ cDeParaSt) .And. dDataLinha <> TRBFR->FPF_DATA 
				//reinicia a data
				If dDataLinha > MV_PAR04
					dDataLinha := MV_PAR03
				EndIf
				While dDataLinha <> TRBFR->FPF_DATA
					If dDataLinha > MV_PAR04
						Exit 
					EndIf
					If cFrotAux <> CLOFRO
						cFrotAux := CLOFRO
						@ NLIN, 000     	 PSAY If(Empty(CLOFRO)	,TRBFR->FPF_FROTA 	,CLOFRO)
						@ NLIN, PCOL()+1	 PSAY If(Empty(CNOME)	,TRBFR->T9_NOME 	,CNOME)
					Else
						@ NLIN, 000     	 PSAY Space(cTamFrot)
						@ NLIN, PCOL()+1	 PSAY Space(cTamNome)
					EndIf
					@ NLIN, PCOL()+1	 PSAY UPPER( LOCR00502("5")) 				//"DISPONIVEL"
					@ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->CLI_OBRA))
					@ NLIN, PCOL()+2	 PSAY SPACE(LEN(TRBFR->MUN_OBRA))
					@ NLIN, PCOL()+1	 PSAY dDataLinha
					//@ NLIN, PCOL()+1	 PSAY MV_PAR04
					NLIN++   
					dDataLinha := dDataLinha+1
					// --> IMPRESSAO DO CABECALHO DO RELATORIO... 
					IF NLIN > 55 // SALTO DE P¡GINA. NESTE CASO O FORMULARIO TEM 55 LINHAS...
						CABEC(TITULO,CABEC1,CABEC2,NOMEPROG,TAMANHO,NTIPO)
						NLIN := 8
					ENDIF 
				EndDo
			EndIf
		//EndIf
      		
		IF !EMPTY(TRBFR->FQ5_CODCLI)
			IF	(TRBFR->FQ5_CODCLI < MV_PAR08 .OR. TRBFR->FQ5_CODCLI > MV_PAR09)
				dDataLinha := TRBFR->FPF_DATA+1
				TRBFR->(DBSKIP())
				LOOP
			ENDIF
		ENDIF

		IF TRBFR->FPF_DATA>MV_PAR04 .OR. TRBFR->FPF_DATA < MV_PAR03
			dDataLinha := TRBFR->FPF_DATA+1
			TRBFR->(DBSKIP())
			LOOP				   					
		ENDIF

		IF !EMPTY(MV_PAR05)
			CQRYLOC := "SELECT * FROM "+RETSQLNAME("FPF")+ " FPF "
			CQRYLOC +=  "WHERE FPF_FROTA  = '"+TRBFR->FPF_FROTA +"' "
			//CQRYLOC +=  "AND FPF_STATUS BETWEEN '"+MV_PAR05+"' AND '"+MV_PAR06+"' "
			If !Empty(cInMvPar05)
				CQUERY += " AND FPF_STATUS IN (" + cInMvPar05 + ") " + CRLF
			EndIf
			CQRYLOC +=  "AND D_E_L_E_T_ = '' AND FPF_FROTA = '' "
			CQRYLOC += "AND ((FPF.FPF_DATA <= "  + DTOS(MV_PAR03) + " AND FPF.FPF_DATA <= " + DTOS(MV_PAR04)  + " AND FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + "  AND FPF.FPF_DATA >= " + DTOS(MV_PAR04) + ") OR "	// PERÕODO TOTALMENTE DENTRO DO LAN«AMENTO
			CQRYLOC += "    (FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + " AND FPF.FPF_DATA <= " + DTOS(MV_PAR04)  + " AND FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + "  AND FPF.FPF_DATA <= " + DTOS(MV_PAR04) + ") OR "	// PERÕODO TOTALMENTE FORA DO LAN«AMENTO
			CQRYLOC += "    (FPF.FPF_DATA <= "  + DTOS(MV_PAR03) + " AND FPF.FPF_DATA <= " + DTOS(MV_PAR04)  + " AND FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + "  AND FPF.FPF_DATA <= " + DTOS(MV_PAR04) + ") OR "	// LAN«AMENTO TERMINA NO PERÕODO
			CQRYLOC += "    (FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + " AND FPF.FPF_DATA <= " + DTOS(MV_PAR04)  + " AND FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + "  AND FPF.FPF_DATA >= " + DTOS(MV_PAR04) + ")) "	// LAN«AMENTO INICIA NO PERÕODO							
			
			CQRYLOC := CHANGEQUERY(CQRYLOC)
			DBUSEAREA(.T., "TOPCONN", TCGENQRY(,,CQRYLOC), "TRBLOC", .F., .T.)
			TCSETFIELD("TRBLOC","FPF_DATA","D",8,0)
			//TCSETFIELD("TRBLOC","FPF_DATA","D",8,0)							
			IF !TRBLOC->(EOF())
				IF TRBLOC->FPF_DATA>MV_PAR04 .OR. TRBLOC->FPF_DATA < MV_PAR03
					dDataLinha := TRBFR->FPF_DATA+1
					TRBFR->(DBSKIP())
					TRBLOC->(DBCLOSEAREA())
					LOOP				   					
				ENDIF
			ENDIF
			TRBLOC->(DBCLOSEAREA())				
		ENDIF
			
		IF !EMPTY(MV_PAR08)
			IF EMPTY(TRBFR->FQ5_CODCLI) .AND. TRBFR->FPF_STATUS == "5"
				dDataLinha := TRBFR->FPF_DATA+1
				TRBFR->(DBSKIP())
				LOOP
			ENDIF
		ENDIF
			
		IF EMPTY(TRBFR->FQ5_CODCLI) .AND. TRBFR->FPF_STATUS <> "5" 
			CQRYLOC := "SELECT * FROM "+RETSQLNAME("FQ5")+ " "
			CQRYLOC +=  "WHERE FQ5_GUINDA  = '"+TRBFR->FPF_FROTA +"' "
			CQRYLOC +=  "AND FQ5_CODCLI BETWEEN '"+MV_PAR08+"' AND '"+MV_PAR09+"' "
			CQRYLOC +=  "AND FQ5_LOJA BETWEEN '"+MV_PAR10+"' AND '"+MV_PAR11+"' AND D_E_L_E_T_ = ''"
			CQRYLOC := CHANGEQUERY(CQRYLOC)
			DBUSEAREA(.T., "TOPCONN", TCGENQRY(,,CQRYLOC), "TRBLOC", .F., .T.)
			IF TRBLOC->(EOF())
				dDataLinha := TRBFR->FPF_DATA+1
				TRBFR->(DBSKIP())
				TRBLOC->(DBCLOSEAREA())
				LOOP				   					
			ENDIF
			TRBLOC->(DBCLOSEAREA())
		ENDIF

		IF TRBFR->FPF_DATA > MV_PAR04
			dDataLinha := TRBFR->FPF_DATA+1
			TRBFR->(DBSKIP())
			LOOP				
		ENDIF
			
		IF !EMPTY(MV_PAR08) .AND. EMPTY(MV_PAR05) .AND. TRBFR->FPF_STATUS <> "5"
			IF SELECT("TRBCLI") > 0
				TRBCLI->(DBCLOSEAREA())
			ENDIF
			CQRYCLI := " SELECT * FROM "+RETSQLNAME("FPF")+ " FPF "
			CQRYCLI += "  WHERE FQ5_CODCLI BETWEEN '"+MV_PAR08+"' AND '"+MV_PAR08+"' " 				
			IF !EMPTY(MV_PAR10) 
				CQRYCLI += "    AND FQ5_LOJA = '"+MV_PAR10+"' "
			ELSE
				CQRYCLI += "    AND FQ5_LOJA = '"+TRBFR->FQ5_LOJA+"' "
			ENDIF
			CQRYCLI += "    AND FPF_FROTA  = '"+TRBFR->FPF_FROTA +"' AND D_E_L_E_T_ = '' AND "				
			CQRYCLI += " ((FPF.FPF_DATA <= "  + DTOS(MV_PAR03) + " AND FPF.FPF_DATA <= " + DTOS(MV_PAR04)  + " AND FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + "  AND FPF.FPF_DATA >= " + DTOS(MV_PAR04) + ") OR "
			CQRYCLI += "  (FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + " AND FPF.FPF_DATA <= " + DTOS(MV_PAR04)  + " AND FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + "  AND FPF.FPF_DATA <= " + DTOS(MV_PAR04) + ") OR "
			CQRYCLI += "  (FPF.FPF_DATA <= "  + DTOS(MV_PAR03) + " AND FPF.FPF_DATA <= " + DTOS(MV_PAR04)  + " AND FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + "  AND FPF.FPF_DATA <= " + DTOS(MV_PAR04) + ") OR "
			CQRYCLI += "  (FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + " AND FPF.FPF_DATA <= " + DTOS(MV_PAR04)  + " AND FPF.FPF_DATA >= "  + DTOS(MV_PAR03) + "  AND FPF.FPF_DATA >= " + DTOS(MV_PAR04) + ")) "						
			CQRYCLI := CHANGEQUERY(CQRYCLI)
			DBUSEAREA(.T., "TOPCONN", TCGENQRY(,,CQRYCLI), "TRBCLI", .F., .T.)
			IF TRBCLI->(EOF())
				IF CLOFRO <> TRBFR->FPF_FROTA 
					IF DDTFIM < TRBFR->FPF_DATA
						DDTFIM := TRBFR->FPF_DATA+1
					ENDIF
					dDataLinha := TRBFR->FPF_DATA+1
					TRBFR->(DBSKIP())
					LOOP						
				ENDIF
				LCONTR := .T.
			ENDIF
			
			TRBCLI->(DBCLOSEAREA())
		ENDIF
		//Data inicial n„o vazia
		IF !EMPTY(CLODTI)
			IF !EMPTY(CLOFRO) .AND. EMPTY(MV_PAR05)
				IF CLOFRO <> TRBFR->FPF_FROTA  .AND. CLODTF < MV_PAR04

					dDataLinha := MV_PAR03

					IF CLODTF < MV_PAR04
						If cFrotAux <> CLOFROX
							cFrotAux := CLOFROX
							@ NLIN, 000     	 PSAY CLOFROX
							@ NLIN, PCOL()+1	 PSAY CNOMEX
						Else
							@ NLIN, 000     	 PSAY Space(cTamFrot)
							@ NLIN, PCOL()+1	 PSAY Space(cTamNome)
						EndIf
						//@ NLIN, 000     	 PSAY CLOFROX
						//@ NLIN, PCOL()+1	 PSAY CFANTX
						//@ NLIN, PCOL()+1	 PSAY CNOMEX
						//@ NLIN, PCOL()+1	 PSAY TRBFR->STATUS 				//"DISPONIVEL"
						@ NLIN, PCOL()+1	 PSAY UPPER(X3Combo("FPF_STATUS", TRBFR->FPF_STATUS)) 				//"DISPONIVEL"
						//@ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->FPO_LOCAL))
						//@ NLIN, PCOL()+1	 PSAY SPACE(LEN(cLocal))
						@ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->CLI_OBRA))
						@ NLIN, PCOL()+2	 PSAY SPACE(LEN(TRBFR->MUN_OBRA))
						@ NLIN, PCOL()+1	 PSAY CLODTF+1
						//@ NLIN, PCOL()+1	 PSAY MV_PAR04
						@ NLIN, PCOL()+2	 PSAY Transform(TRBFR->FPF_HORAI,cPicHora)
						@ NLIN, PCOL()+2	 PSAY Transform(TRBFR->FPF_HORAF,cPicHora)
						NLIN++   
						
						dDataLinha := dDataLinha+1
						// --> IMPRESSAO DO CABECALHO DO RELATORIO... 
						IF NLIN > 55 // SALTO DE P¡GINA. NESTE CASO O FORMULARIO TEM 55 LINHAS...
							CABEC(TITULO,CABEC1,CABEC2,NOMEPROG,TAMANHO,NTIPO)
							NLIN := 8
						ENDIF 
					ENDIF							
				ENDIF
			ENDIF
		ENDIF
			
		//-->> ADICIONADO 14/03/2012
		//IF TRBFR->FPO_DTINI-DDTFIM>1 .AND. !EMPTY(MV_PAR05) .
		/*IF TRBFR->FPF_DATA-DDTFIM>1 .AND. (!EMPTY(MV_PAR05) .OR. "5" $ TRBFR->FPF_STATUS ) .AND. LOK

			@ NLIN, 000     	 PSAY TRBFR->FPF_FROTA                                         
			//@ NLIN, PCOL()+1	 PSAY TRBFR->T9_CODFA    
			@ NLIN, PCOL()+1	 PSAY TRBFR->T9_NOME                     
			@ NLIN, PCOL()+1	 PSAY UPPER( LOCR00502(TRBFR->FPF_STATUS)) 		
			//@ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->FPO_LOCAL))
			//@ NLIN, PCOL()+1	 PSAY SPACE(LEN(cLocal))
			@ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->CLI_OBRA))
			@ NLIN, PCOL()+2	 PSAY SPACE(LEN(TRBFR->MUN_OBRA))
			@ NLIN, PCOL()+1	 PSAY DDTFIM+1
			//@ NLIN, PCOL()+1	 PSAY TRBFR->FPF_DATA-1
			@ NLIN, PCOL()+2	 PSAY Transform(TRBFR->FPF_HORAI,cPicHora)
			@ NLIN, PCOL()+2	 PSAY Transform(TRBFR->FPF_HORAF,cPicHora)
			NLIN++
			
			dDataLinha := dDataLinha+1
			// --> IMPRESSAO DO CABECALHO DO RELATORIO... 
			IF NLIN > 55 // SALTO DE P¡GINA. NESTE CASO O FORMULARIO TEM 55 LINHAS...
				CABEC(TITULO,CABEC1,CABEC2,NOMEPROG,TAMANHO,NTIPO)
				NLIN := 8
			ENDIF 
			LOK := .F.
		ENDIF
		*/	
		IF EMPTY(CLODTF)
			//CLODTF := CTOD(" / / ")	
			CLODTF := MV_PAR04-1
		ENDIF

		CLOFROX	:= TRBFR->FPF_FROTA 
		CFANTX	:= TRBFR->T9_CODFA
		CNOMEX	:= TRBFR->T9_NOME			
			
		IF TRBFR->FPF_STATUS == "5" .AND. CLOFRO <> TRBFR->FPF_FROTA  .AND. CLODTF < MV_PAR04

			If cFrotAux <> CLOFROX
				cFrotAux := CLOFROX
				@ NLIN, 000     	 PSAY CLOFROX
				@ NLIN, PCOL()+1	 PSAY CNOMEX
			Else
				@ NLIN, 000     	 PSAY Space(cTamFrot)
				@ NLIN, PCOL()+1	 PSAY Space(cTamNome)
			EndIf
			//@ NLIN, 000     	 PSAY CLOFROX
			//@ NLIN, PCOL()+1	 PSAY CFANTX
			//@ NLIN, PCOL()+1	 PSAY CNOMEX
			@ NLIN, PCOL()+1	 PSAY UPPER( LOCR00502(TRBFR->FPF_STATUS)) 			// "DISPONIVEL "
			//@ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->FPO_LOCAL))
			//@ NLIN, PCOL()+1	 PSAY SPACE(LEN(cLocal))
			@ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->CLI_OBRA))
			@ NLIN, PCOL()+2	 PSAY SPACE(LEN(TRBFR->MUN_OBRA))
			@ NLIN, PCOL()+1	 PSAY CLODTF+1
			//@ NLIN, PCOL()+1	 PSAY MV_PAR04
			@ NLIN, PCOL()+2	 PSAY Transform(TRBFR->FPF_HORAI,cPicHora)
			@ NLIN, PCOL()+2	 PSAY Transform(TRBFR->FPF_HORAF,cPicHora)
			NLIN++  
			// --> IMPRESSAO DO CABECALHO DO RELATORIO... 
			IF NLIN > 55 // SALTO DE P¡GINA. NESTE CASO O FORMULARIO TEM 55 LINHAS...
				CABEC(TITULO,CABEC1,CABEC2,NOMEPROG,TAMANHO,NTIPO)
				NLIN := 8
			ENDIF 
		ENDIF
		
		NXXX := "OK"
		CLODTI := IF(TRBFR->FPF_DATA < MV_PAR03, MV_PAR03, TRBFR->FPF_DATA)
		CLODTF := IF(TRBFR->FPF_DATA  > MV_PAR04, MV_PAR04, TRBFR->FPF_DATA)
	  		
		//-->> PRIMEIRO DISPONÕVEL
		IF EMPTY(CLOFRO) .AND. (EMPTY(MV_PAR05) .OR. TRBFR->FPF_STATUS == "5") .AND. LOK
			IF CLODTI>MV_PAR03

				If cFrotAux <> TRBFR->FPF_FROTA 
					cFrotAux := TRBFR->FPF_FROTA 
					@ NLIN, 000     	 PSAY TRBFR->FPF_FROTA 
					@ NLIN, PCOL()+1	 PSAY TRBFR->T9_NOME 
				Else
					@ NLIN, 000     	 PSAY Space(cTamFrot)
					@ NLIN, PCOL()+1	 PSAY Space(cTamNome)
				EndIf
				//@ NLIN, 000     	 PSAY TRBFR->FPF_FROTA                                         
				//@ NLIN, PCOL()+1	 PSAY TRBFR->T9_CODFA    
				//@ NLIN, PCOL()+1	 PSAY TRBFR->T9_NOME                     
				@ NLIN, PCOL()+1	 PSAY UPPER( LOCR00502(TRBFR->FPF_STATUS)) 			// "DISPONIVEL"
				//@ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->FPO_LOCAL))
				//@ NLIN, PCOL()+1	 PSAY SPACE(LEN(cLocal))
				@ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->CLI_OBRA))
				@ NLIN, PCOL()+2	 PSAY SPACE(LEN(TRBFR->MUN_OBRA)) 
				@ NLIN, PCOL()+1	 PSAY MV_PAR03    
				//@ NLIN, PCOL()+1	 PSAY CLODTI-1
				@ NLIN, PCOL()+2	 PSAY Transform(TRBFR->FPF_HORAI,cPicHora)
				@ NLIN, PCOL()+2	 PSAY Transform(TRBFR->FPF_HORAF,cPicHora)
				NLIN++   
				// --> IMPRESSAO DO CABECALHO DO RELATORIO... 
				IF NLIN > 55 // SALTO DE P¡GINA. NESTE CASO O FORMULARIO TEM 55 LINHAS...
					CABEC(TITULO,CABEC1,CABEC2,NOMEPROG,TAMANHO,NTIPO)
					NLIN := 8
				ENDIF   
								    
				LOK := .F.
			ENDIF
		ENDIF 
	  		   
		IF TRBFR->FPF_DATA-DDTFIM>1 .AND. CLOFRO==TRBFR->FPF_FROTA  .AND. (EMPTY(MV_PAR05) .OR. TRBFR->FPF_STATUS == "5")
			IF TRBFR->FPF_DATA>=MV_PAR03 .AND. TRBFR->FPF_DATA<=MV_PAR04
				IF DDTFIM+1 > MV_PAR03 .AND. EMPTY(MV_PAR08) .AND. LOK

					If cFrotAux <> TRBFR->FPF_FROTA 
						cFrotAux := TRBFR->FPF_FROTA 
						@ NLIN, 000     	 PSAY TRBFR->FPF_FROTA 
						@ NLIN, PCOL()+1	 PSAY TRBFR->T9_NOME 
					Else
						@ NLIN, 000     	 PSAY Space(cTamFrot)
						@ NLIN, PCOL()+1	 PSAY Space(cTamNome)
					EndIf
					//@ NLIN, 000     	 PSAY TRBFR->FPF_FROTA                                         
					//@ NLIN, PCOL()+1	 PSAY TRBFR->T9_CODFA    
					//@ NLIN, PCOL()+1	 PSAY TRBFR->T9_NOME                     
					@ NLIN, PCOL()+1	 PSAY UPPER( LOCR00502(TRBFR->FPF_STATUS)) 			// "DISPONIVEL"
					//@ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->FPO_LOCAL))
					//@ NLIN, PCOL()+1	 PSAY SPACE(LEN(cLocal))
					@ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->CLI_OBRA))
					@ NLIN, PCOL()+2	 PSAY SPACE(LEN(TRBFR->MUN_OBRA))
					@ NLIN, PCOL()+1	 PSAY DDTFIM+1
					//@ NLIN, PCOL()+1	 PSAY TRBFR->FPF_DATA-1
					@ NLIN, PCOL()+2	 PSAY Transform(TRBFR->FPF_HORAI,cPicHora)
					@ NLIN, PCOL()+2	 PSAY Transform(TRBFR->FPF_HORAF,cPicHora)
					NLIN++
					// --> IMPRESSAO DO CABECALHO DO RELATORIO... 
					IF NLIN > 55 // SALTO DE P¡GINA. NESTE CASO O FORMULARIO TEM 55 LINHAS...
						CABEC(TITULO,CABEC1,CABEC2,NOMEPROG,TAMANHO,NTIPO)
						NLIN := 8
					ENDIF 
					    
				ENDIF
				LOK := .T.
			ENDIF
		ENDIF
	  		
	  		IF !EMPTY(CLOFRO) .AND. CLOFRO<>TRBFR->FPF_FROTA  .AND. (EMPTY(MV_PAR05) .OR. TRBFR->FPF_STATUS == "5")
	  			
				//-->> INICIA O REGISTRO DA NOVA FROTA
				IF MV_PAR03<TRBFR->FPF_DATA .OR. TRBFR->FPF_STATUS = "5" .AND. LOK
					DDT := TRBFR->FPF_DATA-1
					IF LSALTA
						DDTFIM := MV_PAR03
					ELSE
						IF DDTFIM<MV_PAR03
							DDTFIM := MV_PAR03
							CHTML 	+= '<TD>STR0008</TD>' //'       + "DISPONIVEL" + '
							DDTFIM := DDTFIM+1    
						ENDIF
					ENDIF
					IF DDT < MV_PAR03
						DDT := TRBFR->FPF_DATA
					ENDIF
					IF DDT > MV_PAR04
						DDT := MV_PAR04
					ENDIF

					If cFrotAux <> TRBFR->FPF_FROTA 
						cFrotAux := TRBFR->FPF_FROTA 
						@ NLIN, 000     	 PSAY TRBFR->FPF_FROTA 
						@ NLIN, PCOL()+1	 PSAY TRBFR->T9_NOME 
					Else
						@ NLIN, 000     	 PSAY Space(cTamFrot)
						@ NLIN, PCOL()+1	 PSAY Space(cTamNome)
					EndIf
					//@ NLIN, 000     	 PSAY TRBFR->FPF_FROTA                                         
					//@ NLIN, PCOL()+1	 PSAY TRBFR->T9_CODFA     
					//@ NLIN, PCOL()+1	 PSAY TRBFR->T9_NOME                     
					@ NLIN, PCOL()+1	 PSAY UPPER( LOCR00502(TRBFR->FPF_STATUS)) 				// "DISPONIVEL"
					//@ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->FPO_LOCAL))
					//@ NLIN, PCOL()+1	 PSAY SPACE(LEN(cLocal))
					@ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->CLI_OBRA))
					@ NLIN, PCOL()+2	 PSAY SPACE(LEN(TRBFR->MUN_OBRA))
					@ NLIN, PCOL()+1	 PSAY MV_PAR03
					//@ NLIN, PCOL()+1	 PSAY DDT  
					@ NLIN, PCOL()+2	 PSAY Transform(TRBFR->FPF_HORAI,cPicHora)
					@ NLIN, PCOL()+2	 PSAY Transform(TRBFR->FPF_HORAF,cPicHora)
					NLIN++

					// --> IMPRESSAO DO CABECALHO DO RE	LATORIO... 
					IF NLIN > 55 // SALTO DE P¡GINA. NESTE CASO O FORMULARIO TEM 55 LINHAS...
						CABEC(TITULO,CABEC1,CABEC2,NOMEPROG,TAMANHO,NTIPO)
						NLIN := 8
					ENDIF 
				   			
					LOK := .F.
				ENDIF
			
				DDTFIM := TRBFR->FPF_DATA
			
			ENDIF
			
			IF CLODTI>=MV_PAR03 .AND. CLODTF<=MV_PAR04 
				IF TRBFR->FQ5_LOJA>=MV_PAR10 .AND. TRBFR->FQ5_LOJA<=MV_PAR11 .AND. ALLTRIM(UPPER(X3Combo("FPF_STATUS", TRBFR->FPF_STATUS)))<>"DISPONIVEL"

					If cFrotAux <> TRBFR->FPF_FROTA 
						cFrotAux := TRBFR->FPF_FROTA 
						@ NLIN, 000     	 PSAY TRBFR->FPF_FROTA 
						@ NLIN, PCOL()+1	 PSAY TRBFR->T9_NOME 
					Else
						@ NLIN, 000     	 PSAY Space(cTamFrot)
						@ NLIN, PCOL()+1	 PSAY Space(cTamNome)
					EndIf
					//@ NLIN, 000      PSAY TRBFR->FPF_FROTA                                         
					//@ NLIN, PCOL()+1 PSAY TRBFR->T9_CODFA    
					//@ NLIN, PCOL()+1 PSAY TRBFR->T9_NOME                     
					@ NLIN, PCOL()+1 PSAY UPPER( LOCR00502(TRBFR->FPF_STATUS))  	// TRBFR->STAT_FR  ////Retorna descriÁ„o do combo box do campo FPF_STATUS  
					//@ NLIN, PCOL()+1 PSAY TRBFR->FPO_LOCAL    
					//@ NLIN, PCOL()+1 PSAY cLocal    
			

					CMUNOBRA := TRBFR->MUN_OBRA   
					CCLIOBRA := TRBFR->CLI_OBRA
					
					IF ALLTRIM(CCLIOBRA)=="/"
						CCLIOBRA := ""
					ENDIF

					nColMunObr := 122
					
					@ NLIN, PCOL()+1 PSAY PADR(CCLIOBRA, LEN(TRBFR->CLI_OBRA))           
					@ NLIN, nColMunObr PSAY PADR(CMUNOBRA, LEN(TRBFR->MUN_OBRA))    
					@ NLIN, PCOL()+1 PSAY CLODTI    
					//@ NLIN, PCOL()+1 PSAY CLODTF 
					@ NLIN, PCOL()+2	 PSAY Transform(TRBFR->FPF_HORAI,cPicHora)
					@ NLIN, PCOL()+2	 PSAY Transform(TRBFR->FPF_HORAF,cPicHora)
				
					CLO_CLI	:= CCLIOBRA
					CLO_MUN	:= CMUNOBRA
			
					NLIN := NLIN + 1 // AVANCA A LINHA DE IMPRESSAO
					
					dDataLinha := TRBFR->FPF_DATA+1

					// --> IMPRESSAO DO CABECALHO DO RELATORIO... 
					IF NLIN > 55 // SALTO DE P¡GINA. NESTE CASO O FORMULARIO TEM 55 LINHAS...
						CABEC(TITULO,CABEC1,CABEC2,NOMEPROG,TAMANHO,NTIPO)
						NLIN := 8
					ENDIF 
					
				ENDIF
				LOK := .T.
			ENDIF
		    
			CLOFRO	:= TRBFR->FPF_FROTA 
			CFANT	:= TRBFR->T9_CODFA
			CNOME	:= TRBFR->T9_NOME
	        CLOSTAT	:= TRBFR->FPF_STATUS		
			CLOFROX	:= TRBFR->FPF_FROTA 
			CFANTX	:= TRBFR->T9_CODFA
			CNOMEX	:= TRBFR->T9_NOME
	
		ENDIF
	
	ELSE
	
		//IF MV_PAR05 == "1"
		If "5" $ cDeParaSt .And. TRBFR->FPF_STATUS $ cDeParaSt 
		
			IF NCONT == 0
				NXXX := "OK"
				IF MV_PAR03<=TRBFR->FPF_DATA
					IF TRBFR->FPF_DATA>=MV_PAR03 //.AND. TRBFR->FPO_DTFIM<=MV_PAR04
						IF MV_PAR03 <= TRBFR->FPF_DATA
							DDT := TRBFR->FPF_DATA-1
							IF DDT > MV_PAR04
								DDT := MV_PAR04
							ENDIF
							//IF EMPTY(TRBFR->FPO_LOCAL) .AND. EMPTY(TRBFR->STAT_FR) 
							IF EMPTY(TRBFR->A1_NREDUZ) .AND. EMPTY(TRBFR->FPF_STATUS) 
								DDT := TRBFR->FPF_DATA
							ENDIF

				     		If cFrotAux <> TRBFR->FPF_FROTA 
								cFrotAux := TRBFR->FPF_FROTA 
								@ NLIN, 000     	 PSAY TRBFR->FPF_FROTA 
								@ NLIN, PCOL()+1	 PSAY TRBFR->T9_NOME 
							Else
								@ NLIN, 000     	 PSAY Space(cTamFrot)
								@ NLIN, PCOL()+1	 PSAY Space(cTamNome)
							EndIf
							//@ NLIN, 000     	 PSAY TRBFR->FPF_FROTA                                         
						    //@ NLIN, PCOL()+1	 PSAY TRBFR->T9_CODFA    
						   // @ NLIN, PCOL()+1	 PSAY TRBFR->T9_NOME                     
						    @ NLIN, PCOL()+1	 PSAY UPPER( LOCR00502(TRBFR->FPF_STATUS)) 				//"DISPONIVEL	"
						    //@ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->FPO_LOCAL))
						    //@ NLIN, PCOL()+1	 PSAY SPACE(LEN(cLocal))
						    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->CLI_OBRA))
						    @ NLIN, PCOL()+2	 PSAY SPACE(LEN(TRBFR->MUN_OBRA))
						    @ NLIN, PCOL()+1	 PSAY MV_PAR03    
						   // @ NLIN, PCOL()+1	 PSAY DDT
						   @ NLIN, PCOL()+2	 PSAY Transform(TRBFR->FPF_HORAI,cPicHora)
							@ NLIN, PCOL()+2	 PSAY Transform(TRBFR->FPF_HORAF,cPicHora)
						    NLIN++

							dDataLinha := TRBFR->FPF_DATA+1
							// --> IMPRESSAO DO CABECALHO DO RELATORIO... 
							IF NLIN > 55 // SALTO DE P¡GINA. NESTE CASO O FORMULARIO TEM 55 LINHAS...
								CABEC(TITULO,CABEC1,CABEC2,NOMEPROG,TAMANHO,NTIPO)
								NLIN := 8
							ENDIF 
							
						ENDIF							
					ENDIF
				ENDIF
				LSALTA := .F. 
				CLOFRO	:= TRBFR->FPF_FROTA 			
			ELSE			
				IF TRBFR->FPF_DATA-DDTFIM>1
					IF TRBFR->FPF_DATA>=MV_PAR03 //.AND. TRBFR->FPO_DTFIM<=MV_PAR04						
						IF DDTFIM <= MV_PAR04
							DDT := TRBFR->FPF_DATA-1
							IF LSALTA
								DDTFIM := MV_PAR03
							ELSE
								IF DDTFIM<MV_PAR03
									DDTFIM := MV_PAR03
								ELSE
									DDTFIM := DDTFIM+1    
									CHTML += '<TD>STR0008</TD>' //'       + "DISPONIVEL" + '
							ENDIF
							IF DDT > MV_PAR04
								DDT := MV_PAR04
							ENDIF
							//IF EMPTY(TRBFR->FPO_LOCAL) .AND. EMPTY(TRBFR->STAT_FR) 
							IF EMPTY(TRBFR->A1_NREDUZ) .AND. EMPTY(TRBFR->FPF_STATUS) 
								DDT := TRBFR->FPF_DATA
							ENDIF							
							//-->> ALTERADO 14/03 23:59HS
							IF DDTFIM <= MV_PAR04

					     		If cFrotAux <> TRBFR->FPF_FROTA 
									cFrotAux := TRBFR->FPF_FROTA 
									@ NLIN, 000     	 PSAY TRBFR->FPF_FROTA 
									@ NLIN, PCOL()+1	 PSAY TRBFR->T9_NOME 
								Else
									@ NLIN, 000     	 PSAY Space(cTamFrot)
									@ NLIN, PCOL()+1	 PSAY Space(cTamNome)
								EndIf
								//@ NLIN, 000     	 PSAY TRBFR->FPF_FROTA                                         
							    //@ NLIN, PCOL()+1	 PSAY TRBFR->T9_CODFA    
							    //@ NLIN, PCOL()+1	 PSAY TRBFR->T9_NOME                     
							    @ NLIN, PCOL()+1	 PSAY UPPER( LOCR00502(TRBFR->FPF_STATUS)) 				// "DISPONIVEL	"
							    //@ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->FPO_LOCAL))
							    //@ NLIN, PCOL()+1	 PSAY SPACE(LEN(cLocal))
							    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->CLI_OBRA))
							    @ NLIN, PCOL()+2	 PSAY SPACE(LEN(TRBFR->MUN_OBRA))
							    @ NLIN, PCOL()+1	 PSAY DDTFIM    
							   	// @ NLIN, PCOL()+1	 PSAY DDT
							   	@ NLIN, PCOL()+2	 PSAY Transform(TRBFR->FPF_HORAI,cPicHora)
								@ NLIN, PCOL()+2	 PSAY Transform(TRBFR->FPF_HORAF,cPicHora)
							    NLIN++

								dDataLinha := TRBFR->FPF_DATA+1
								// --> IMPRESSAO DO CABECALHO DO RELATORIO... 
								IF NLIN > 55 // SALTO DE P¡GINA. NESTE CASO O FORMULARIO TEM 55 LINHAS...
									CABEC(TITULO,CABEC1,CABEC2,NOMEPROG,TAMANHO,NTIPO)
									NLIN := 8
								ENDIF 
								
							ENDIF
							LSALTA := .F.
						ENDIF
					ENDIF
				ENDIF
				IF !EMPTY(CLOFROX) .AND. CLOFROX <> TRBFR->FPF_FROTA 
					IF NCONT > 1

						IF (TRBFR->FPF_DATA>=MV_PAR03 /*.AND. TRBFR->FPO_DTFIM<=MV_PAR04*/) .OR. (MV_PAR04 > DDTFIM)
							IF DDTFIM<=MV_PAR04
									CHTML += '<TD>STR0008</TD>' //'       + "DISPONIVEL" + '
									//IF LSALTA										
									//	DDTFIM := MV_PAR03
									//ELSE
										DDTFIM := DDTFIM+1
									//ENDIF
								ELSE
									DDTFIM := MV_PAR03
								ENDIF

					     		If cFrotAux <> CLOFROX 
									cFrotAux := CLOFROX
									@ NLIN, 000     	 PSAY CLOFROX
									@ NLIN, PCOL()+1	 PSAY CNOMEX 
								Else
									@ NLIN, 000     	 PSAY Space(cTamFrot)
									@ NLIN, PCOL()+1	 PSAY Space(cTamNome)
								EndIf
								//@ NLIN, 000     	 PSAY CLOFROX
							    //@ NLIN, PCOL()+1	 PSAY CFANTX
							    //@ NLIN, PCOL()+1	 PSAY CNOMEX
							    @ NLIN, PCOL()+1	 PSAY UPPER( LOCR00502(TRBFR->FPF_STATUS)) 			// "DISPONIVEL	"
							    //@ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->FPO_LOCAL))
							    //@ NLIN, PCOL()+1	 PSAY SPACE(LEN(cLocal))
							    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->CLI_OBRA))
							    @ NLIN, PCOL()+2	 PSAY SPACE(LEN(TRBFR->MUN_OBRA))
							    @ NLIN, PCOL()+1	 PSAY DDTFIM
							   	// @ NLIN, PCOL()+1	 PSAY MV_PAR04
							   	@ NLIN, PCOL()+2	 PSAY Transform(TRBFR->FPF_HORAI,cPicHora)
								@ NLIN, PCOL()+2	 PSAY Transform(TRBFR->FPF_HORAF,cPicHora)
							    NLIN++
							    
								dDataLinha := TRBFR->FPF_DATA+1
								// --> IMPRESSAO DO CABECALHO DO RELATORIO... 
								IF NLIN > 55 // SALTO DE P¡GINA. NESTE CASO O FORMULARIO TEM 55 LINHAS...
									CABEC(TITULO,CABEC1,CABEC2,NOMEPROG,TAMANHO,NTIPO)
									NLIN := 8
								ENDIF 
							ENDIF
							IF MV_PAR03< TRBFR->FPF_DATA-1
								DDT := TRBFR->FPF_DATA-1
								IF DDT > MV_PAR04
									DDT := MV_PAR04
								ENDIF
								//IF EMPTY(TRBFR->FPO_LOCAL) .AND. EMPTY(TRBFR->STAT_FR) 
								IF EMPTY(TRBFR->A1_NREDUZ) .AND. EMPTY(TRBFR->FPF_STATUS) 
									DDT := TRBFR->FPF_DATA
								ENDIF																			

					     		If cFrotAux <> TRBFR->FPF_FROTA  
									cFrotAux := TRBFR->FPF_FROTA 
									@ NLIN, 000     	 PSAY TRBFR->FPF_FROTA 
									@ NLIN, PCOL()+1	 PSAY TRBFR->T9_NOME 
								Else
									@ NLIN, 000     	 PSAY Space(cTamFrot)
									@ NLIN, PCOL()+1	 PSAY Space(cTamNome)
								EndIf
								//@ NLIN, 000     	 PSAY TRBFR->FPF_FROTA 
							    //@ NLIN, PCOL()+1	 PSAY TRBFR->T9_CODFA
							    //@ NLIN, PCOL()+1	 PSAY TRBFR->T9_NOME
							    @ NLIN, PCOL()+1	 PSAY UPPER( LOCR00502(TRBFR->FPF_STATUS)) 			// "DISPONIVEL	"
							    //@ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->FPO_LOCAL))
							    @ NLIN, PCOL()+1	 PSAY SPACE(LEN(cLocal))
							    //@ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->CLI_OBRA))
							    @ NLIN, PCOL()+2	 PSAY SPACE(LEN(TRBFR->MUN_OBRA))
							    @ NLIN, PCOL()+1	 PSAY MV_PAR03
							    //@ NLIN, PCOL()+1	 PSAY DDT
								@ NLIN, PCOL()+2	 PSAY Transform(TRBFR->FPF_HORAI,cPicHora)
								@ NLIN, PCOL()+2	 PSAY Transform(TRBFR->FPF_HORAF,cPicHora)
							    NLIN++
								
								dDataLinha := TRBFR->FPF_DATA+1
								// --> IMPRESSAO DO CABECALHO DO RELATORIO... 
								IF NLIN > 55 // SALTO DE P¡GINA. NESTE CASO O FORMULARIO TEM 55 LINHAS...
									CABEC(TITULO,CABEC1,CABEC2,NOMEPROG,TAMANHO,NTIPO)
									NLIN := 8
								ENDIF 
								LSALTA := .F.
							ENDIF
						ENDIF
						DDTFIM := TRBFR->FPF_DATA
					ENDIF
	            ENDIF
				CLOFRO	:= TRBFR->FPF_FROTA 			
				
			ENDIF
			
			CLOFROX	:= TRBFR->FPF_FROTA 
			CFANTX	:= TRBFR->T9_CODFA
			CNOMEX	:= TRBFR->T9_NOME
			CLOSTAT	:= TRBFR->FPF_STATUS		
			CLODTF := IF(TRBFR->FPF_DATA  > MV_PAR04, MV_PAR04, TRBFR->FPF_DATA)
			
		ENDIF			
		
	ENDIF

	IF DDTFIM < TRBFR->FPF_DATA
		DDTFIM := TRBFR->FPF_DATA
	ENDIF
	
	NCONT++
	dDataLinha := TRBFR->FPF_DATA+1

	TRBFR->(DBSKIP()) // AVANCA O PONTEIRO DO REGISTRO NO ARQUIVO
		   
ENDDO

IF EXISTF .AND. !EMPTY(NXXX)
				CHTML += '<TD>' + STR0008 + 't</TD>' //'       + "DISPONIVEL" + '
	TRBFR->(DBSKIP(-1)) 
	
	IF EMPTY(MV_PAR05) .OR. CLOSTAT == "5"
		IF DDTFIM<MV_PAR04 
			//DDTFIM := DDTFIM+1
			DDTFIM := CLODTF+1
			IF EMPTY(CLOSTAT) 
				DDTFIM := MV_PAR03
			ENDIF
			If cFrotAux <> CLOFROX 
				cFrotAux := CLOFROX
				@ NLIN, 000     	 PSAY CLOFROX
				@ NLIN, PCOL()+1	 PSAY CNOMEX
			Else
				@ NLIN, 000     	 PSAY Space(cTamFrot)
				@ NLIN, PCOL()+1	 PSAY Space(cTamNome)
			EndIf
			//@ NLIN, 000     	 PSAY CLOFROX
		    //@ NLIN, PCOL()+1	 PSAY CFANTX
		   // @ NLIN, PCOL()+1	 PSAY CNOMEX
		    @ NLIN, PCOL()+1	 PSAY "DISPONIVEL	"
		    @ NLIN, PCOL()+1	 PSAY SPACE(40)
		    @ NLIN, PCOL()+1	 PSAY SPACE(60)
		    @ NLIN, PCOL()+2	 PSAY SPACE(23)
		    @ NLIN, PCOL()+1	 PSAY DDTFIM
		    //@ NLIN, PCOL()+1	 PSAY MV_PAR04
			@ NLIN, PCOL()+2	 PSAY Transform(TRBFR->FPF_HORAI,cPicHora)
			@ NLIN, PCOL()+2	 PSAY Transform(TRBFR->FPF_HORAF,cPicHora)
		    NLIN++
			
			// --> IMPRESSAO DO CABECALHO DO RELATORIO... 
			IF NLIN > 55 // SALTO DE P¡GINA. NESTE CASO O FORMULARIO TEM 55 LINHAS...
				CABEC(TITULO,CABEC1,CABEC2,NOMEPROG,TAMANHO,NTIPO)
				NLIN := 8
			ENDIF 
		ENDIF
	ELSE
		IF MV_PAR05 == "5"
			IF MV_PAR04>=DDTFIM
				DDTFIM := DDTFIM+1
				IF EMPTY(CLOSTAT) 
					DDTFIM := MV_PAR03
				ENDIF
				
				If cFrotAux <> CLOFROX 
					cFrotAux := CLOFROX
					@ NLIN, 000     	 PSAY CLOFROX
					@ NLIN, PCOL()+1	 PSAY CNOMEX
				Else
					@ NLIN, 000     	 PSAY Space(cTamFrot)
					@ NLIN, PCOL()+1	 PSAY Space(cTamNome)
				EndIf
				//@ NLIN, 000     	 PSAY CLOFROX
			    //@ NLIN, PCOL()+1	 PSAY CFANTX
			    //@ NLIN, PCOL()+1	 PSAY CNOMEX
			    @ NLIN, PCOL()+1	 PSAY "DISPONIVEL	"
			    @ NLIN, PCOL()+1	 PSAY SPACE(40)
			    @ NLIN, PCOL()+1	 PSAY SPACE(60)
			    @ NLIN, PCOL()+2	 PSAY SPACE(23)
			    @ NLIN, PCOL()+1	 PSAY DDTFIM
			    //@ NLIN, PCOL()+1	 PSAY MV_PAR04
			    NLIN++
				
				// --> IMPRESSAO DO CABECALHO DO RELATORIO... 
				IF NLIN > 55 // SALTO DE P¡GINA. NESTE CASO O FORMULARIO TEM 55 LINHAS...
					CABEC(TITULO,CABEC1,CABEC2,NOMEPROG,TAMANHO,NTIPO)
					NLIN := 8
				ENDIF 
			ENDIF
		ENDIF
	ENDIF

ENDIF

//roda uma ultima vez para garantir que ira apresentar no final do registro
//Se for Status vazio ou 5-DisponÌvel, apresenta data se n„o retornou na Query
If (Empty(cDeParaSt) .Or. "5" $ cDeParaSt) .And. dDataLinha <> MV_PAR04 

	While dDataLinha <= MV_PAR04
		If cFrotAux <> CLOFRO 
			cFrotAux := CLOFRO
			@ NLIN, 000     	 PSAY CLOFRO
			@ NLIN, PCOL()+1	 PSAY CNOME
		Else
			@ NLIN, 000     	 PSAY Space(cTamFrot)
			@ NLIN, PCOL()+1	 PSAY Space(cTamNome)
		EndIf
		//@ NLIN, 000     	 PSAY CLOFRO
		//@ NLIN, PCOL()+1	 PSAY CNOME
		@ NLIN, PCOL()+1	 PSAY UPPER( LOCR00502("5")) 				//"DISPONIVEL"
		@ NLIN, PCOL()+1	 PSAY SPACE(LEN(TRBFR->CLI_OBRA))
		@ NLIN, PCOL()+2	 PSAY SPACE(LEN(TRBFR->MUN_OBRA))
		@ NLIN, PCOL()+1	 PSAY dDataLinha
		//@ NLIN, PCOL()+1	 PSAY MV_PAR04
		NLIN++   
		dDataLinha := dDataLinha+1
		// --> IMPRESSAO DO CABECALHO DO RELATORIO... 
		IF NLIN > 55 // SALTO DE P¡GINA. NESTE CASO O FORMULARIO TEM 55 LINHAS...
			CABEC(TITULO,CABEC1,CABEC2,NOMEPROG,TAMANHO,NTIPO)
			NLIN := 8
		ENDIF 
	EndDo
EndIf
	
TRBFR->(DBCLOSEAREA())                                          	

//IF MV_PAR15 == 1		// SE FOR EXPORTAR PARA O EXCEL
	/*
	CHTML := ' </TABLE></BODY></HTML>'+CRLF
	FWRITE(NARQ,CHTML,LEN(CHTML))
	FCLOSE(NARQ)								// FECHAMOS O ARQUIVO PADR√O HTML
	CPYS2T(GETSRVPROFSTRING("STARTPATH","")+CARQUIVO, ALLTRIM(GETTEMPPATH()), .T.)	// COPIA ARQUIVO HTML DO SERVER\SYSTEM P/ TEMPOR¡RIO DO CLIENTE
	FERASE(CARQUIVO)							// REMOVE ARQUIVO DO SERVER\SYSTEM

	IF APOLECLIENT("MSEXCEL") 	// SE TEM EXCEL NO CLIENTE. ABRIMOS O EXCEL COM O ARQUIVO HTML
		OEXCELAPP := MSEXCEL():NEW()
		OEXCELAPP:WORKBOOKS:OPEN(ALLTRIM(GETTEMPPATH()) + CARQUIVO)
		OEXCELAPP:SETVISIBLE(.T.)
		OEXCELAPP:DESTROY()
	ELSE						//SE N√O ENCONTROU O EXCEL, O S.O. DECIDE COMO ABRIR
		SHELLEXECUTE("OPEN",ALLTRIM(GETTEMPPATH()) + CARQUIVO,"","",1)
	ENDIF
	*/
//ENDIF

SET DEVICE TO SCREEN

IF ARETURN[5]==1
   DBCOMMITALL()
   SET PRINTER TO
   OURSPOOL(WNREL)
ENDIF

MS_FLUSH()

RETURN



/*
‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹‹
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
±±⁄ƒƒƒƒƒƒƒƒƒƒ¬ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒø±±
±±≥DESCRIáÖO ≥ PROCESSAMENTO E EXECUCAO DO RELATORIO                        ≥±±
±±√ƒƒƒƒƒƒƒƒƒƒ≈ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒ¥±±
±±≥ USO      ≥ ESPECIFICO GPO                                               ≥±±
±±¿ƒƒƒƒƒƒƒƒƒƒ¡ƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒƒŸ±±
±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±±
ﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂﬂ
*/
STATIC FUNCTION VALIDPERG(CPERG)
/*
CPERG := PADR(CPERG,10)

PUTSX1(CPERG,"01","FROTA DE?   ","","","MV_CH1","C",16,00,00,"G","","ST9 ","","","MV_PAR01","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"02","FROTA ATE?  ","","","MV_CH2","C",16,00,00,"G","","ST9 ","","","MV_PAR02","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"03","PERIODO DE? ","","","MV_CH3","D",08,00,00,"G","NAOVAZIO()","    ","","","MV_PAR03","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"04","PERIODO ATE?","","","MV_CH4","D",08,00,00,"G","NAOVAZIO()","    ","","","MV_PAR04","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"05","STATUS DE?  ","","","MV_CH5","C",01,00,00,"G","","ZL  ","","","MV_PAR05","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"06","STATUS ATE? ","","","MV_CH6","C",01,00,00,"G","","ZL  ","","","MV_PAR06","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"07","ASG DE?     ","","","MV_CH7","C",27,00,00,"G","","DTQA","","","MV_PAR07","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"08","ASG ATE?    ","","","MV_CH8","C",27,00,00,"G","","DTQA","","","MV_PAR08","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"09","CLIENTE DE? ","","","MV_CH9","C",06,00,00,"G","","CLI ","","","MV_PAR09","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"10","CLIENTE ATE?","","","MV_CHA","C",06,00,00,"G","","CLI ","","","MV_PAR10","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"11","LOJA DE?    ","","","MV_CHB","C",02,00,00,"G","","    ","","","MV_PAR11","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"12","LOJA ATE?   ","","","MV_CHC","C",02,00,00,"G","","    ","","","MV_PAR12","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"13","OBRA DE?    ","","","MV_CHD","C",03,00,00,"G","","    ","","","MV_PAR13","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"14","OBRA ATE?   ","","","MV_CHE","C",03,00,00,"G","","    ","","","MV_PAR14","","","","","","","","","","","","","","","","",,,,"")
PUTSX1(CPERG,"15","EXPORTA EXCEL?","","","MV_CHF","N",01,0,0,"C","","      ","","","MV_PAR15","SIM","","","","N√O","","" ,"","","","","","","","","")
*/
RETURN

//------------------------------------------------------------------------------
/*/{Protheus.doc} LOCR00502
Pesquisa do STATUS no Pergunte LOCR005
@author Jose Eulalio
@since 21/11/2022
/*/
//------------------------------------------------------------------------------
Function LOCR00501(l1Elem,lTipoRet)
Local cTitulo	:=""
Local cCombo	:= ""
Local MvPar
Local MvParDef	:=""
Local nTam		:= 0

Private aSit:={}

l1Elem := If (l1Elem = Nil , .F. , .T.) //se permite apenas 1 elemento

Default lTipoRet := .T.

cAlias := Alias() 					 // Salva Alias Anterior

/*IF lTipoRet
	MvPar:=Rtrim(&(Alltrim(ReadVar())))			 // Carrega Nome da Variavel do Get em Questao
	mvRet:=Alltrim(ReadVar())			 // Iguala Nome da Variavel ao Nome variavel de Retorno
	nTam := Len(&mvRet)
EndIf*/

MvPar := "MV_PAR05"
MvRet := "MV_PAR05"

cCombo := AllTrim(GetSX3Cache("FPF_STATUS", "X3_CBOX")) // FPF_STATUS 	1=Prevista;2=Confirmada;3=Baixada;4=Encerrada;5=Cancelada;6=Medida

aSit := StrToKarr(cCombo,";")

aSit[5] := "5=Disponivel"

MvParDef:="123456"
cTitulo :="Status"  //"Situacao"

nTam 	:= Len(aSit)

IF lTipoRet
	IF f_Opcoes(@MvPar,cTitulo,aSit,MvParDef,12,49,l1Elem,1,nTam,.T.)  // Chama funcao f_Opcoes
		&MvRet := mvpar                                                                          // Devolve Resultado
	EndIf	
EndIf
//PAREI AQUI
dbSelectArea(cAlias) 	
							 // Retorna Alias
Return( IF( lTipoRet , .T. , MvParDef ) )

//------------------------------------------------------------------------------
/*/{Protheus.doc} LOCR00502
Retorna descriÁ„o do combo box do campo FPF_STATUS
@author Jose Eulalio
@since 21/11/2022
/*/
//------------------------------------------------------------------------------
Function LOCR00502(cStatFPF)
Local cRetorno 	:= "Disponivel"
Local nX		:= 0
Local aSit		:= {}

cCombo := AllTrim(GetSX3Cache("FPF_STATUS", "X3_CBOX")) // FPF_STATUS 	1=Prevista;2=Confirmada;3=Baixada;4=Encerrada;5=Cancelada;6=Medida

aSit := StrToKarr(cCombo,";")

For nX := 1 To len(aSit)
	If cStatFPF $ aSit[nX]
		If At("5",aSit[nX]) > 0
			cRetorno := "Disponivel"
		Else
			cRetorno := SubStr(aSit[nX],At("=",aSit[nX])+1)
		EndIf
		Exit
	EndIf
Next nX

Return cRetorno
