#include "tlpp-core.th"

namespace totvs.protheus.backoffice.reconciliation.newdataexport

//-------------------------------------------------------------------
/*/{Protheus.doc} NewDataExportService
Classe de serviço, realizada instância e chamada de métodos de serviços

@author Totvs
/*/
//-------------------------------------------------------------------
class NewDataExportService
    public method new()
    public method getInstance()
    public method getAllNewDataExport()
endclass

//-------------------------------------------------------------------
/*/{Protheus.doc} NewDataExportService
Metodo construtor

@author Totvs
/*/
//-------------------------------------------------------------------
method new() class NewDataExportService
return

//-------------------------------------------------------------------
/*/{Protheus.doc} NewDataExportService
Responsável por instanciar a classe controller

@author Totvs
/*/
//-------------------------------------------------------------------
method getInstance() class NewDataExportService
    static __instance As Object
    
    If ValType(__instance) == "U"
        __instance := NewDataExportService():new()
    EndIf
return

//-------------------------------------------------------------------
/*/{Protheus.doc} getAllNewDataExport
Responsável por chamar a consulta e parsear o retorno no formato JSON

@author Totvs
/*/
//-------------------------------------------------------------------
method getAllNewDataExport(nPage as Numeric, nPageSize as Numeric) class NewDataExportService
    Local oSettings := NewDataExportProtheusData():getData() As Object
    Local cDadosExcel := "" as Character
    Local aResponse := {} as Array

    cDadosExcel := oSettings:getAll()

    If ValType(cDadosExcel) == "C" .And. !Empty(cDadosExcel)                                                         
        aAdd(aResponse, .T.)
        aAdd(aResponse, cDadosExcel)            
    Else            
        aAdd(aResponse, .F.)
        aAdd(aResponse, "Erro na exportação dos dados para excel")    
    EndIf

    FreeObj(oSettings)

return aResponse
