#Include "tlpp-core.th"
#Include "tlpp-rest.th"

Namespace totvs.protheus.health.plans.api.familyContract.blockProtocol

/*/{Protheus.doc} BlockProtocolsController
Classe controladora das APIs de Solicitação de Cancelamento de Planos

@type class
@author Guilherme Carreiro da Silva
@since 01/04/2023
@version Protheus 12
/*/
Class BlockProtocolsController

    Private Data oService As Object

    Public Method new() Constructor

    @POST("/totvsHealthPlans/familyContract/v1/blockProtocols")
    Public Method apiPostBlockProtocols()

EndClass

/*/{Protheus.doc} new
Método construtor da classe

@type method
@author Guilherme Carreiro da Silva
@since 01/04/2023
@version Protheus 12
/*/
Method new() Class BlockProtocolsController
Return Self

/*/{Protheus.doc} apiPostBlockProtocols
Método responsável por enviar a solicitação do cancelamento
de planos
Url: /totvsHealthPlans/familyContract/v1/blockProtocols
Verbo: POST

@type Method
@author Guilherme Carreiro da Silva
@since 01/04/2023
@version Protheus 12
/*/
Method apiPostBlockProtocols() Class BlockProtocolsController

    Local cBody := oRest:getBodyRequest() As Json

    Self:oService := BlockProtocolsService():new()

    If Self:oService:setBodyString(cBody, "E001")
        If Self:oService:postBlockProtocols()
            oRest:setResponse(Self:oService:getJsonResult())
            oRest:setStatusCode(Self:oService:getStatusCode())
        Else
            oRest:setFault(Self:oService:getJsonResult())
            oRest:setStatusCode(Self:oService:getStatusCode())
        EndIf
    Else
        oRest:setFault(Self:oService:getJsonResult())
        oRest:setStatusCode(Self:oService:getStatusCode())
    EndIf

    oRest:setKeyHeaderResponse("Content-Type", "application/json")

Return
