#INCLUDE "tlpp-core.th"
#INCLUDE "PROTHEUS.CH"

using namespace ac.Reopening.OfStock.Service
using namespace ac.acCalc.Repository
using namespace ac.acBalanceClosing.Repository
using namespace ac.acStockClosing.Repository
using namespace ac.acContab.Repository

/*/{Protheus.doc} nomeFunction
    (long_description)
    @type  Function
    @author user
    @since date
    @version version
    @param param, param_type, param_descr
    @return return, return_type, return_description
    @example
    (examples)
    @see (links_or_references)
    /*/
Function IniProc282(cBranch,cCompany,cFilsProc, cIdParent, cIdChild, ltotal, cIdProccess, lReopeningSb9, ddataClosing, cUserNamek, aFilsProc)
    Local objectReopen
    local oJourney    :=  acJourneyLog():New()
    IniEnviron(cCompany,cBranch,'EST282')
    oJourney:insertTable(cIdParent, cIdChild, 'EST282', 'SETUP', cUserNamek)
    objectReopen := ac.Reopening.OfStock.Service.acReopeningOfStockServ():new()
    objectReopen:eventInitialProces(cBranch,cCompany,cFilsProc, cIdParent, cIdChild, ltotal, cIdProccess, lReopeningSb9, ddataClosing, cUserNamek, aFilsProc)
Return 


/*/{Protheus.doc} IniProcRep
    (long_description)
    @type  Function
    @author user
    @since date
    @version version
    @param param, param_type, param_descr
    @return return, return_type, return_description
    @example
    (examples)
    @see (links_or_references)
    /*/
Function IniProcRep(aParansfil, dDateClosin, cIdParent, cIdChild, cIdGrandson, cUserNameJ,cfil, cCompany)

    Local objectReopen
    local oJourney    :=  acJourneyLog():New()
    IniEnviron(cCompany,cfil,'REPAIR')
    oJourney:insertTable(cidChild, cIdGrandson, 'REPAIR', 'SETUP', cUserNameJ)
    objectReopen := ac.Reopening.OfStock.Service.acReopeningOfStockServ():new()
    objectReopen:eventInitialProcesRepair(aParansfil, dDateClosin, cIdParent, cidChild,cIdGrandson, cUserNameJ)

Return 

/*/{Protheus.doc} IniProc330

    (long_description)
    @type  Function
    @author user
    @since date
    @version version
    @param param, param_type, param_descr
    @return return, return_type, return_description
    @example
    (examples)
    @see (links_or_references)
    /*/
Function IniProc330(aListaFil,lCPParte,aParAuto,cId, cIdChild, cCompany, cBranch, cUserNameJ, cAcUserId, lExecAuto,cDataBase)

Local oStartJob  := ac.acCalc.Repository.acCalcRep():New()
    oStartJob:eventRec330(aListaFil,lCPParte,aParAuto,cId, cIdChild,cCompany,cBranch,cUserNameJ, cAcUserId, lExecAuto,cDataBase)
Return

/*/{Protheus.doc} IniEnviron
    Função de inicialização de ambiente
    @type  Function
    @author user
    @since date
    /*/
 Function IniEnviron(cCompany,cBranch,cFunName,cDataBase)
  Default cDataBase := ""

  RPCSETTYPE(3)
  RPCSETENV(cCompany,cBranch,,,'EST',cFunName )

  If !Empty(cDataBase)
      dDataBase := cToD(cDataBase)
  EndIf

Return 


/*/{Protheus.doc} IniProc350
    (long_description)
    @type  Function
    @author user
    @since date
    @version version
    @param param, param_type, param_descr
    @return return, return_type, return_description
    @example
    (examples)
    @see (links_or_references)
    /*/
Function IniProc350(aFilList, cId, cIdChild,cCompany,cBranch, cUsernameJ, cAcUserId)
Local oStartJob  := ac.acBalanceClosing.Repository.acBalanceClosing():New()
    oStartJob:eventRec350(aFilList, cId, cIdChild, cCompany,cBranch, cUsernameJ, cAcUserId)
Return


/*/{Protheus.doc} IniProc280
    (long_description)
    @type  Function
    @author user
    @since date
    @version version
    @param param, param_type, param_descr
    @return return, return_type, return_description
    @example
    (examples)
    @see (links_or_references)
/*/
Function IniProc280(cData, aListaFil, aParAuto, cCompany, cBranch, cId, cIdChild, cUsernamej, cAcUserId)

Local oStockClosingRep  := ac.acStockClosing.Repository.acStockClosingRep():New()
oStockClosingRep:eventStockClosing280(cData, aListaFil, aParAuto, cCompany, cBranch, cId, cIdChild,cUserNameJ, cAcUserId)

Return


/*/{Protheus.doc} IniProc331
    (long_description)
    @type  Function
    @author user
    @since date
    @version version
    @param param, param_type, param_descr
    @return return, return_type, return_description
    @example
    (examples)
    @see (links_or_references)
/*/
Function IniProc331(aListaFil, aParAuto, cCompany, cBranch, cId, cIdChild, cUsernamej, cAcUserId,cDataBase)

Local oContabRep  := ac.acContab.Repository.acContabRep():New()
oContabRep:eventCont331(aListaFil, aParAuto, cCompany, cBranch, cId, cIdChild,cUserNameJ, cAcUserId,cDataBase)

Return

/*/{Protheus.doc} IniVarEnAc
    Inicializa variaveis publicas com informacoes do usuario logado no ambiente setado pelo Acompanha Custos
    @type Function
    @author Squad.Entradas
    @since 14/09/2022
    @version 1.0
    @param  cAcUserId , character, codigo do usuario
            cAcUsrName, character, nome do usuario
    /*/
Function IniVarEnAc(cAcUserId, cAcUsrName)

    If Type("__cUserId") == "C" .And. Empty(__cUserId)
        __cUserId := cAcUserId
    EndIf

    If Type("cUserName") == "C" .And. Empty(cUserName)
        cUserName := cAcUsrName
    EndIf

Return
