#include "tlpp-core.th"
#include "tlpp-rest.th"

namespace ac.Warehouse.Service
using namespace ac.Warehouse.Repository

Class acWarehouseService
    public Method New()
    public Method getWarehouses()
EndClass

/*/{Protheus.doc} acWarehouseService:New()
    @type  Metodo
    @author felipe.suetoshi
    @since  Abril 28, 2021
    @version 12.1.27
/*/
Method new() class acWarehouseService    
return Self

/*/{Protheus.doc} getWarehouses:New()
    Metodo responsavel por retornar uma lista de armazens com base na filial
    @type  Metodo
    @author felipe.suetoshi
    @since  Abril 28, 2021
    @version 12.1.27
/*/
Method getWarehouses(nPage, nPageSize, aFilter) class acWarehouseService

    Local oRepository as Object
    Local oResponse   as Object

    oResponse := JsonObject():New()
    oRepository := ac.Warehouse.Repository.acWarehouseRepository():new()
    oResponse := oRepository:getWarehouses(nPage, nPageSize, aFilter)

return oResponse
