#INCLUDE 'protheus.ch'
#INCLUDE 'restful.ch'

//-------------------------------------------------------------------
/*/{Protheus.doc} PLSAuthorizationsDaoBEA

@author  sakai
@version P12
@since   06/09/22
/*/
//------------------------------------------------------------------- 
class PLSAuthorizationsDaoBEA from PLSAuthorizationsDao
    
    Public Method New()
    Private Method getCampos()
    Public Method buscaGuia()
    Public Method bscGuiaPrestadorReenvio()
    Public Method vldReenvioHAT(cMatric, cCodRda)

EndClass


Method New(cGuia) class PLSAuthorizationsDaoBEA
    
    _Super:New(cGuia)
    
Return self


Method getCampos() class PLSAuthorizationsDaoBEA

    Local cCampos := ""

    //Campos BEA
    cCampos += " BEA_CID, BEA_LOCAL, BEA_SENHA, BEA_INDACI, BEA_TIPADM, BEA_PROATE, BEA_TIPATE, BEA_DATPRO, "
    cCampos += " BEA_STATUS, BEA_TIPGUI, BEA_TIPFAT, BEA_INDCLI, BEA_TIPSAI, BEA_TIPCON, BEA_AUSVLD, "  
    cCampos += " BEA_DPTETA, BEA_CODRDA, BEA_GUIPRE, BEA_CODLOC, BEA_ATERNA, BEA_VALSEN, BEA_LIBERA, "
    cCampos += " BEA_CDPFSO, BEA_CDPFRE, BEA_DATSOL, BEA_GUIPRI, BEA_TOKEDI, BEA_CODESP, BEA_STALIB, "
    cCampos += " BEA_SIGLA,  BEA_ESTSOL, BEA_REGSOL, BEA_ESPSOL, BEA_SIGEXE, BEA_ESTEXE, BEA_REGEXE, "
    cCampos += " BEA_OPEUSR, BEA_CODEMP, BEA_MATRIC, BEA_TIPREG, BEA_DIGITO, "
    cCampos += " BEA_OPEMOV, BEA_ANOAUT, BEA_MESAUT, BEA_NUMAUT, "
    //Campos BE4
    cCampos += " BE4_DTALTA, BE4_HRALTA, BE4_PRVINT, BE4_TIPINT, BE4_TIPALT "

Return cCampos

Method buscaGuia() class PLSAuthorizationsDaoBEA

    Local cQuery := ""
    Local lFound := .F.

    cQuery += " SELECT "
    cQuery += self:getCampos()

    cQuery += " FROM " + RetSqlName("BEA")+" BEA "
    cQuery += " LEFT JOIN " + RetSqlName("BE4") + " BE4"
	cQuery += "   ON BE4_FILIAL = '"  + xFilial("BE4")+ "' "
	cQuery += "   AND BEA_OPEMOV = BE4_CODOPE "
	cQuery += "   AND BEA_ANOAUT = BE4_ANOINT "
	cQuery += "   AND BEA_MESAUT = BE4_MESINT "
	cQuery += "   AND BEA_NUMAUT = BE4_NUMINT "
	cQuery += "   AND BE4.D_E_L_E_T_ = ' ' "
    cQuery += " WHERE BEA_FILIAL = '" + xFilial("BEA") +"' "	
    cQuery += "   AND BEA_OPEMOV = '" + Substr(self:cGuia,01,04) + "' "
    cQuery += "   AND BEA_ANOAUT = '" + Substr(self:cGuia,05,04) + "' "
    cQuery += "   AND BEA_MESAUT = '" + Substr(self:cGuia,09,02) + "' "
    cQuery += "   AND BEA_NUMAUT = '" + Substr(self:cGuia,11,08) + "' "
    cQuery += "   AND BEA.D_E_L_E_T_ = ' ' "
   
    self:setQuery(cQuery)
	lFound := self:executaQuery()

Return lFound

Method bscGuiaPrestadorReenvio(cMatric, cCodRda, cLoteTiss) class PLSAuthorizationsDaoBEA

    Local cQuery := ""
    Local lFound := .F.

    cQuery += " SELECT "
    cQuery += self:getCampos()

    cQuery += " FROM " + RetSqlName("BEA")+" BEA "
    cQuery += " LEFT JOIN " + RetSqlName("BE4") + " BE4"
	cQuery += "   ON BE4_FILIAL = '"  + xFilial("BE4")+ "' "
	cQuery += "   AND BEA_OPEMOV = BE4_CODOPE "
	cQuery += "   AND BEA_ANOAUT = BE4_ANOINT "
	cQuery += "   AND BEA_MESAUT = BE4_MESINT "
	cQuery += "   AND BEA_NUMAUT = BE4_NUMINT "
	cQuery += "   AND BE4.D_E_L_E_T_ = ' ' "
    cQuery += " WHERE BEA_FILIAL = '" + xFilial("BEA") +"' "
    cQuery += "   AND BEA_OPEUSR = '" + Substr(cMatric,01,4) + "' "
    cQuery += "   AND BEA_CODEMP = '" + Substr(cMatric,05,4) + "' "
    cQuery += "   AND BEA_MATRIC = '" + Substr(cMatric,09,6) + "' "
    cQuery += "   AND BEA_TIPREG = '" + Substr(cMatric,15,2) + "' "
    cQuery += "   AND BEA_DIGITO = '" + Substr(cMatric,17,1) + "' "
    cQuery += "   AND BEA_CODRDA = '" + cCodRda + "' "
    cQuery += "   AND BEA_DATPRO = '" + Dtos(dDataBase)  + "' "
    cQuery += "   AND BEA_LOTGUI = '" + cLoteTiss + "' "
    cQuery += "   AND BEA.D_E_L_E_T_ = ' ' "
   
    self:setQuery(cQuery)
	lFound := self:executaQuery()

Return lFound

Method vldReenvioHAT(cMatric, cCodRda) class PLSAuthorizationsDaoBEA

    Local cQuery := ""
    Local lFound := .F.
    Local lRet   := .T.

    cQuery += " SELECT "
    cQuery += self:getCampos()

    cQuery += " FROM " + RetSqlName("BEA")+" BEA "
    cQuery += " LEFT JOIN " + RetSqlName("BE4") + " BE4 "
	cQuery += "   ON BE4_FILIAL = '"  + xFilial("BE4")+ "' "
	cQuery += "   AND BEA_OPEMOV = BE4_CODOPE "
	cQuery += "   AND BEA_ANOAUT = BE4_ANOINT "
	cQuery += "   AND BEA_MESAUT = BE4_MESINT "
	cQuery += "   AND BEA_NUMAUT = BE4_NUMINT "
	cQuery += "   AND BE4.D_E_L_E_T_ = ' ' "
    cQuery += " WHERE BEA_FILIAL = '" + xFilial("BEA") +"' "
    cQuery += "   AND BEA_OPEUSR = '" + Substr(cMatric,01,4) + "' "
    cQuery += "   AND BEA_CODEMP = '" + Substr(cMatric,05,4) + "' "
    cQuery += "   AND BEA_MATRIC = '" + Substr(cMatric,09,6) + "' "
    cQuery += "   AND BEA_TIPREG = '" + Substr(cMatric,15,2) + "' "
    cQuery += "   AND BEA_DIGITO = '" + Substr(cMatric,17,1) + "' "
    cQuery += "   AND BEA_CODRDA = '" + cCodRda + "' "
    cQuery += "   AND BEA_DATPRO = '" + Dtos(dDataBase)  + "' "
    cQuery += "   AND BEA.D_E_L_E_T_ = ' ' "
   
    self:setQuery(cQuery)
	lFound := self:executaQuery()

    //Se achou a guia, retorna falso pois nao podera realizar o reenvio
    if lFound
        lRet := .F.
        
        cAliTrb := self:getAliasTemp()
        while !self:isEof()
            aadd(self:aGuiasPrest,(cAliTrb)->(BEA_OPEMOV+BEA_ANOAUT+BEA_MESAUT+BEA_NUMAUT))
            self:dbSkip()
        endDo

    endIf

Return lRet