#include "tlpp-core.th"
#include "tlpp-rest.th"

namespace tr.cancelReceipt

using namespace tr.util
using namespace tr.cancelReceipt.Service

//-------------------------------------------------------------------
/*/{Protheus.doc} totvsRecibos/cancelReceipt
	
	EndPoint  
	
	URL http://localhost:8080/rest/api/v1/totvsRecibos/receipt/cancelReceipt

	 
@author José González
@since 26/07/2022
/*/
//-------------------------------------------------------------------
class cancelReceiptController

    public data  oResponse
    public method New()

    @Post('/api/v1/totvsRecibos/receipt/cancelReceipt')
    public method postCancelReceipt(Character,JsonObject)
    
endclass
//-------------------------------------------------------------------
/*/{Protheus.doc} totvsRecibos/cancelReceipt
new
Constructor de la clase

@author José González
@since 26/07/2022
/*/
//-------------------------------------------------------------------
//Method new() class cancelReceiptController   
//return 

//-------------------------------------------------------------------
/*/{Protheus.doc} totvsRecibos/cancelReceipt
EndPoint  para Anular  el recibo seleccionado

@author José González
@since 26/07/2022
/*/
//-------------------------------------------------------------------
 
Method postCancelReceipt(cBody,jResponse) Class cancelReceiptController

	Local oCancelReceiptService as Object
	Local jBody
	Local cBodyContent 

	jBody := JsonObject():New()
	cBodyContent := jBody:fromJson(cBody)

	oCancelReceiptService := cancelReceiptService():new()
	jResponse := oCancelReceiptService:getcancelReceiptService(jBody)
	
	
Return nil
